### ISSUE TITLE
Auto Archive Messages after so long.

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Joomla-Bible-Study#126]
Look at making archive system and then we may even look into a auto trash after so many years. In a way make it zip all that content at that time up so they can store it in a backup system.

**Comment by bcordis** [comment]
Move to Bate2

**Comment by bcordis** [comment]
Moving to next version as this did not make it in

**Comment by bcordis** [comment]
With auto-archive will need a plugin to trigger this for us. Almost need a proclaim plugin that is just for these auto tasks?

**Comment by tomfuller2** [comment]
Yes. Makes sense
