### ISSUE TITLE
Improved Media File manager

### ISSUE THREAD

**Issue by genu** [Joomla-Bible-Study/Joomla-Bible-Study#148]
Currently, media files can consist of many sources: third party servers, local server, direct file upload, and third party components.

To simplify adding media files, maybe we should make this workflow somewhat similar to how the **menu manger** functions.

That is, a user first selects the type of media they want to add, then they are given options to configure that particular media type. For example, if they choose to use a *third party server* as a media type, they are shown only the configuration settings for that particular media type.

The benefit of this is that the media file manager would no longer show all the types of media that can be added and their settings if they are not even used. For example, there is no purpose of showing to the user a file upload field if they always use a third party server for their media.

Doing this will make this part of the component less confusing for users.

**Comment by bcordis** [comment]
Closing as this is part of the new uploader.
