### ISSUE TITLE
Multi-language Support

### ISSUE THREAD

**Issue by dsgrant07** [Joomla-Bible-Study/Joomla-Bible-Study#271]
Studies are translated into many different languages. The different translations should in some way be related i.e. it is considered as one study in different languages and not separate studies. The studies that are displayed should be dependent on user’s selected language.

**Comment by bcordis** [comment]
@dsgrant07 Can you reach out to me ASAP need your input on some of the changes.

**Comment by bcordis** [comment]
Closing as we have made this possible in this version.
