### ISSUE TITLE
Rethinking Servers and Mediafiles

### ISSUE THREAD

**Issue by genu** [Joomla-Bible-Study/Joomla-Bible-Study#284]
I briefly discussed this with @tomfuller2 and @bcordis, but I thought I'd summarize the plan, and some design choices that, perhaps, may require feedback.

### Current implementation
**Servers** Alias stored in the databases to any server. Used on the frontend to construct media links.
**folders** Alias to specific folders on any server. Used on the frontend to construct media links.
**Mediafiles** Can be stored anywhere, and link is constructed dynamically based on filename and selected **servers** and **folder**.

#### Issues
* Excessive configuration due to the amount and type of media files.

#### Media Sources and Endpoints
Rename **servers** to **sources**, and introduce the **endpoint** entity. Examples of endpoints include: *Local*, *AmazonS3*, *YouTube*, *Vimeo*, etc.

**Endpoints** are categorized as follows:
* **alias**: Referencing an entity inside joomla (e.g. Joomla Article, DOCmon file, etc)
* **storage**: Referencing a source where files can be stored (e.g. FTP, S3, Local)
* **service**: Referencing a source that services media to the user (e.g. Youtube, Vimeo)

#### Justification
By having endpoints, users can upload media directly to the endpoint. For example, by configuring a YouTube endpoint, a user can upload videos directly to youtube through the component, select youtube videos directly from their youtube channel; all within the JBS component.

**Endpoints** have independent configurations, depending on the endpoint and don't have any component dependencies.

An example endpoint:
```xml
<endpoint type="storage">
    <name>FTP</name>
    <description>Connect to third party FTP servers. FTP credentials are required in order to connect successfully.</description>

    <fieldset name="params">
        <fields name="params">
            <field name="hostname" type="text" label="*Hostname*" description="*FTP_Hostname*"/>
            <field name="port" type="text" label="*FTP_PORT*" description="*FTP_PORT*"/>
            <field name="username" type="text" label="*Username*" description="*FTP Username*"/>
            <field name="password" type="password" label="*Password*" description="*Password description*"/>
        </fields>
    </fieldset>
</endpoint>
```
A **source** simply refers to an **endpoint** that has been setup, and configured.

#### Media Files
When adding a media file, the user must first choose a **source**. Based on the source, the type of media that the user can add is determined by the **endpoint** that the **source** has configured. For example, if the **endpoint** type is a **service**, the user is restricted on the type of media that they can upload.

**Comment by bcordis** [comment]
Are we ready to close this? @genu

**Comment by tomfuller2** [comment]
The long explanation should be part of an article Eugen needs to write for
version 9 help on the JBS site

**Comment by bcordis** [comment]
Yes I think it should be included in the post install message also. To point to the new way we are going to do servers.
