### ISSUE TITLE
Module Styling

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#323]
Need to have module show title from the module menu, not just the header from our module parameters.

Need a way for module to get styling from a suffix. Perhaps a suffix needs to be applied to all styles if given?

**Comment by bcordis** [comment]
Are we looking into this? @tomfuller2

**Comment by tomfuller2** [comment]
The module should follow the same styling as the component.
default_main.php uses $list = $JBSMListing->getFluidListing($items, $params, $admin_params, $template, $type = "sermons");

**Comment by tomfuller2** [comment]
This has been addressed I think.
