### ISSUE TITLE
Development environments with Vagrant

### ISSUE THREAD

**Issue by genu** [Joomla-Bible-Study/Joomla-Bible-Study#326]
I've been experimenting in using [Vagrant](http://www.vagrantup.com/) for setting up a development environment. In summary [Vagrant](http://www.vagrantup.com/) simply allows for setting up a dev environment that you can share with other developers. That way, we no longer will need XAMPP or MAMP, LAMP, etc, since we can set that up once with vagrant and then share the vagrant machine with the repository.

In theory this would make development a bit easier because there won't be any configuration necessary.

This enhancement is **NOT** relevant to the JBS component itself, its mainly for easy of development.

**Comment by mheiniger** [comment]
Vagrant even got better, because they now also integrate docker.io, which is much more lightweight and faster than the virtualbox container used before.

**Comment by bcordis** [comment]
That sounds good @genu was trying virtualbox but was having trouble with it.

**Comment by bcordis** [comment]
@mheiniger What is your status on this. Have you worked on this at all?

**Comment by mheiniger** [comment]
No, i didn't work on that. It was just a hint that those technologies can help developers to setup the project and start coding, independent if their operating system is windows, mac or linux. If you want i can investigate in that topic.

**Comment by bcordis** [comment]
@mheiniger That would be cool if you have time.  But if you have time on other issues you can tack on would be greate. Can you email me directly so we can discuss this.

**Comment by bcordis** [comment]
Email me at skeebrent@gmail.com ASAP.

**Comment by mwweb** [comment]
I would like to throw in that I have been utilizing a Vagrant Box for over a year for development. I prefer it over XAMPP, WAMP, or other options, as it run the box in a virtual box of your preferred operating system.

I would actually recommend to people to check out JoomlaTools Vagrant. They created a Vagrant box geared towards Joomla! developers. It runs on Ubuntu, and want to create a new dev site instance? No problem. Simply enter joomla site:create {sitename} in the console, the Joomlatools box will download and install the latest version of joomla, and update the host file, etc.

Plus they already have xdebug installed, composer, a mail catcher, and so much more.

[https://www.joomlatools.com/developer/tools/vagrant/](url)

**Comment by bcordis** [comment]
Closed as support for this has faded and development staff is lacking to support.
