### ISSUE TITLE
Multi Language for Media Files

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#351]
This request comes from Karen Elrick - she designed the look of JBS up until 8.1.0
Sure - it's http://oicjapan.org
. Notice that most (lately, almost all) messages have PDFs in both English and Japanese. I created the little icons with EN and JP on them, and then created two custom records in the bsms_mimetype and bsms_media tables to differentiate the two. But if you had a Language field in the bsms_mediafiles table, that would be a more natural way to take care of that. Then in the Component Wide Settings you could let the user decide whether they will be using the Language field or not (is their media multilingual) - if not (probably the default), you can hide it in the admin side and also not have the extra space on the front end. But if they turn on Multi-Language, then when they specify a Language for their media files, you could denote the language next to the media icon with either the two-letter abbreviation or a small flag.

I don't know if you have made any consolidated input capability for studies and files in the new version or not (in the super-old version I worked with, putting in all the data was very cumbersome), but I didn't want the church staff to have to input all that stuff every week, so I used RS!Forms to write a couple of custom forms for doing that. All the staff person needs to do is fill out one form, and when the form is processed, a large chunk of PHP code I wrote will populate all the Bible Study tables with the appropriate data and put the files in the right place (and rename them to something logical - I use the message date and language abbreviation). Here is a screenshot showing our Recent Messages sidebar, the User Menu that only shows when staff is logged in, and the form:

![dcbbdigc](https://cloud.githubusercontent.com/assets/1281117/3422039/ea138d32-ff12-11e3-8bdf-c6242e1acecc.png)

As you may notice on the User Menu, there is also a second form called "Add to Existing Message" that is for uploading additional files after the message record has already been created:

![fighcfjj](https://cloud.githubusercontent.com/assets/1281117/3422041/f9a9de04-ff12-11e3-9fab-31e089ca246b.png)

I hope that some of this is automated in your current version. For example, in the version I have, if you use the admin interface, you have to manually enter the size of the file you are uploading. I just let PHP get that information from the file and use it to populate the database. I wanted to do that with the duration of the audio, but I couldn't figure out how.

Since my Wordpress plugin prospects fizzled, I'm hoping the JBS data conversion isn't too hard. Meanwhile, now that I finally have it working again, I'll start familiarizing myself with the new interface and layout.

**Comment by bcordis** [comment]
Working correctly now. Will need to work of doc on how this works. 
Closing unless bug is found.
