### ISSUE TITLE
New teacher; taken from list of Joomla user

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#374]
Entering a new teacher, try to take a user out of Joomla system. I got no entry in the list, so I cannot select anybody. This appears if user is 'public' or 'registered'.

**Comment by bcordis** [comment]
Is this fixed?

**Comment by st-anton** [comment]
I cannot see a dropdown box at all; the only thing I can see is a box to enter text.

**Comment by st-anton** [comment]
Maybe the text in the teachers form is misunderstanding. The field in the Backend Teacher edit display says: `Contacts:` and the tooltip says: `Choose a contact instead of filling this form. This overrides any duplicate fields from this form`.
So I expect a dropdown menu with the Joomla users. Selecting one of them fills in the other fields or set some kind of link to the Joomla users.
Does thsi meet the intention?

**Comment by tomfuller2** [comment]
So it looks like the ability to select a contact for the teacher has been removed from the form? @bcordis did you do this?

**Comment by bcordis** [comment]
Not that I remember doing any of that. Should be still available.

On Monday, March 23, 2015, Tom Fuller <notifications@github.com> wrote:

> So it looks like the ability to select a contact for the teacher has been
> removed from the form? @bcordis <https://github.com/bcordis> did you do
> this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/374#issuecomment-85231265>
> .
>


-- 
Sent from Gmail Mobile

**Comment by tomfuller2** [comment]
The Contacts is there but just a blank field. Not working.

**Comment by tomfuller2** [comment]
@bcordis - the admin/views/teacher/tmpl/edit.php uses javascript or something that I don't understand starting around line 87. You'll have to take a look for us.

**Comment by bcordis** [comment]
Ok I'll look into it.

**Comment by st-anton** [comment]
I tried in my current website (Joomla 2.5 with BS 8.0.0). There it does not work as well.
![user](https://cloud.githubusercontent.com/assets/2517417/7229300/6fa03756-e762-11e4-893d-9009c08dd104.png)
So: Is there a use of it? Can we drop this feature?

**Comment by bcordis** [comment]
Right now we don't use it. It was to pull contact info form the users info.

**Comment by bcordis** [comment]
Fixed problem with selection.

**Comment by st-anton** [comment]
Now I can see the modal popup. But: 
What do I make wrong? I have some users:
![users](https://cloud.githubusercontent.com/assets/2517417/7462947/df875672-f2b5-11e4-9b59-98fc9ccb3291.png)

But I cannot select anybody, because the selection is not populated:
![contact](https://cloud.githubusercontent.com/assets/2517417/7462969/f6223744-f2b5-11e4-9c67-0fbc6f226015.png)

**Comment by bcordis** [comment]
@st-anton well I think we are looking at this in a different way. This field links to contacts not to users. This could be where we are seeing the error?

**Comment by st-anton** [comment]
You are right. I did not use contacts in the past, so I mixed up users and contacts. This works now.
Closed.
