### ISSUE TITLE
Media Images view missing from 9.0

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#403]
The mediaimages and mediaimage views appear to have been removed from the admin side. This is functionality that should not have been removed. It is used by a lot of admins to create custom images and types. Please put this back if you removed it.

**Comment by tomfuller2** [comment]
I see that images are tied to servers. This can't be the case. Admins need to be able to choose one server with multiple image types - unless you mean for an admin to create a different server entry for each media type? I'm not sure this is a good thing.
Also - after opening and saving the server I still get this error on the mediafiles list page:
Warning: simplexml_load_file(): I/O warning : failed to load external entity "/home1/joomlaor/public_html/joomlaoregon_com/jbs/administrator/components/com_biblestudy/addons/servers//.xml" in /home1/joomlaor/public_html/joomlaoregon_com/jbs/administrator/components/com_biblestudy/models/server.php on line 100

This is from installing 8.0.8, then importing an existing db, and installing 9.0.0 over the top. Upgrade seemed successful.

**Comment by tomfuller2** [comment]
Also, only speaker and podcast video images came through - not the YouTube image I had created. Podcast video will not play and YouTube link does not show up at all. 
http://joomlaoregon.com/jbs/index.php/component/biblestudy/sermons/1

**Comment by bcordis** [comment]
The images setting under a server is only for pulling default values to when a media is added.

**Comment by tomfuller2** [comment]
OK. We will also need a target field (a text field) or a drop down. For instance, see my church site http://calvarynewberg.org/bible-studies. The green leaf is a pdf direct link that needs to open in a new window. I didn't see that in the server defaults.

**Comment by bcordis** [comment]
Should that default come from server or admin params?

**Comment by bcordis** [comment]
I'm more inclined from the admin params.

**Comment by tomfuller2** [comment]
The admin will need to change it according to an individual media file record. My mp3 does NOT use _blank, only the pdf.
Another problem - the default of descending doesn't seem to work. I can't seem to use debug - Php errors out when I have debug on saying too much memory used.

**Comment by bcordis** [comment]
That is possible under the media add dialogue. If we need to make it per mime type that could be different.

I'm working on making a mime type list for them to use.

**Comment by tomfuller2** [comment]
I notice that the image selector in the media file record itself is also non-functional. It's just a text box. We need to add back in the image capability for the admin to add images and also select one from a drop down.

**Comment by bcordis** [comment]
Fixed image selector now it would work. Also we can make a set folder for media images.

**Comment by tomfuller2** [comment]
I'm trying to run down what is happening in the upgrade.
When going from 8.0.8 to 9.0:
1. We need to set a default image as the speaker icon (otherwise the admin has to upload a new image rather than use the ones we have by default - in fact, why not give them access to the folder where those images reside?)

2. Though "type" legacy is created, when the admin chooses the mediafiles list, it errors because it can't find $addon from server model line 97. I assume that variable comes from models/mediafiles line 58. But when I dump $items the type is null. 

3. Why do we require an image? Images come from individual media files, NOT from servers. It's also required but the field is buried and not obvious where it's located. This will cause confusion.

If I go in and open and save a server record, it still doesn't help with mediafiles.

**Comment by bcordis** [comment]
@tomfuller2 Lets do a call to sort this out.
@genu 

Let me know when ASAP.

**Comment by tomfuller2** [comment]
I'm on now

**Comment by bcordis** [comment]
Closed ase we moved to media manager.
