### ISSUE TITLE
Finder: Missing phrase 'Studies'

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#406]
Backend: Filter -> Any type of content -> studies only

**Comment by bcordis** [comment]
@st-anton what view is this happening in?

**Comment by st-anton** [comment]
In the component finder, there is a view 'index'. The index can be filtered for public/hidden as well as the individual plugins (categories, weblinks, articles and so on). Here 'Studies' appears as well.
I got nearer: \administrator\components\com_finder\helpers\html\finder.php  line 36 gets the finder types, line 56 tries to find a phrase PLG_FINDER_QUERY_FILTER_BRANCH_P_STUDIES. But unfortunatelly, the language file is not loaded, because it is not present in  JROOT/administrator/language/en-GB/en-GB.JBS_PLG_FINDER.ini
--> Again, there is a problem, that the language file is encapsulated in the plugin / component and not in the common language folder.

I don't know a workaround for this. Hacking the com_finder is not tolerable. Let's close this.

**Comment by st-anton** [comment]
Currently the finder component does not use local language files, but CORE language folder only. Also see #438.

**Comment by bcordis** [comment]
@st-anton is there a way to put it into the plugin to call the language file?

**Comment by st-anton** [comment]
Hm, I don't find a hook to latch to. And in fact - it is one phrase, so it is not that important.
Let's see, whether Joomla com_finder will be fixed.

**Comment by bcordis** [comment]
@st-anton So what is are solution here?

**Comment by st-anton** [comment]
No solution. Just close this. Maybe in the future Joomla will extend the core looking into the local language files.
Closed
