### ISSUE TITLE
Name: 'Joomla Bible Study' or 'Bible Study'?

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#410]
I see, that the 'Joomla' is more and more dropped out of the name. Also the 'official' extension name is now 'Bible Study'.
Should this be corrected in all language files? Also in the header (Copyright (C) 2007 - 2015 ~~Joomla~~ Bible Study. All rights reserved.)

**Comment by bcordis** [comment]
@tomfuller2 @st-anton We need to settle on one name as the way we are coding right now is Joomla Bible Study or JBSM.

**Comment by st-anton** [comment]
I skimmed the Joomla! extensions and found roughly 100 extensions with the name 'xxx for Joomla' like 'Canva for Joomla' and about 10 extensions named 'xxx Joomla yyy' (like 'Hot Joomla Gallery') - among 8700 extensions. Thus I tend to 'Bible Study' without the prefix Joomla.

**Comment by st-anton** [comment]
I try to summarize:
- Only very view extensions use the name 'Joomla'
- The official name in extensions directory is 'Bible Study'
- 6 out of 7 extensions in the backend extension manager claim 'Bible Study' - except Smart Search
- The backend components menue also says 'Bible Study'
My conclusion: Let's go for 'Bible Study'.
For the moment, php code and language keys should stick to 'JBSM...' or 'JBS_'
Do you agree?

**Comment by tomfuller2** [comment]
I don't really care either way. When I created it I used the name Bible
Study, which is the name on the Joomla Extensions Directory. But when I
created the website I added Joomla into the name - this was approved by the
JED folks.

**Comment by tomfuller2** [comment]
Let's go with Anton's suggestion - stick with Bible Study. Maybe in the future we switch to Bible Study for Joomla. BUT - let's leave any code acronymns the same - these shouldn't depend on the name. For instance - earlier I named all the tables BSMS_tablename as in: "Bible Study Message System" but never actually used that name.
