### ISSUE TITLE
Frontend -> Edit Message: Publish Up / Down missing?

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#411]
In the frontend -> edit message, the publish up and publish down seem to be missing.
(\com_biblestudy\views\messageform\tmpl\edit.php  line 300 and up)

**Comment by bcordis** [comment]
Waiting on @genu to finish the uploader. This should be added into the new view once that is don.

**Comment by bcordis** [comment]
completed.
