### ISSUE TITLE
Component 'Update' crashes

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#412]
Having a new installation with latest Bible Study version (from branch development). 'Updating' this with the same version will crash: Fatal error: Class 'JBSMDbHelper' not found in ...\administrator\components\com_biblestudy\install\updates\6.1.1.php on line 36

**Comment by bcordis** [comment]
Should fix this error.

**Comment by st-anton** [comment]
Does not crash that hard :-O
Error: 1060 Duplicate column name 'show_level' SQL=ALTER TABLE `fmnj33_bsms_studies` ADD COLUMN show_level VARCHAR(100) NOT NULL DEFAULT '0' AFTER user_name

**Comment by bcordis** [comment]
Can you send me the DB that you are using to migrate with or install. I've tested on quite a few and don't get that error.

**Comment by st-anton** [comment]
Quite simple :-)
Install the component on a fresh Joomla. Install the same again. That's all.

**Comment by bcordis** [comment]
@st-anton let me know if there is still a bug on migration or can we close this issue.

**Comment by st-anton** [comment]
I think, it's not critical to leave this as it is. If the user install the same version of BS without uninstalling, the error can be tolerated.

**Comment by bcordis** [comment]
Is this still showing up?

**Comment by st-anton** [comment]
Yes, simply install the component twice.
