### ISSUE TITLE
Unclear warning in administration page

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#413]
I need to investigate in this. Maybe has to do with language work??
Run the Administrator page:
Warning: simplexml_load_file(): I/O warning : failed to load external entity &quot;file:///.../administrator/components/com_biblestudy/biblestudy.xml&quot; in ...\libraries\cms\installer\installer.php on line 2148

Stack:
7	1.2093	3949416	require_once( '...\administrator\components\com_biblestudy\biblestudy.php' )	..\helper.php:352
8	1.3172	4723296	JControllerLegacy->execute( )	..\biblestudy.php:44
9	1.3172	4723352	BiblestudyController->display( )	..\legacy.php:730
10	1.3208	4793048	JControllerLegacy->display( )	..\controller.php:120
11	1.3346	5405824	BiblestudyViewAdmin->display( )	..\legacy.php:693
12	1.4337	7327536	JInstaller::parseXMLInstallFile( )	..\view.html.php:236
13	1.4337	7327728	simplexml_load_file ( )	..\installer.php:2148

**Comment by bcordis** [comment]
This is do to the xml file was not copied to the proper directory or you or you incorectory created a symbolic link. Look at that.

**Comment by st-anton** [comment]
Thanks for the hint. It was a failure in handling, I deleted the file by mistake.
Don't need to be fixed.
