### ISSUE TITLE
Release date?

### ISSUE THREAD

**Issue by koleror** [Joomla-Bible-Study/Joomla-Bible-Study#414]
Hi folks!
Thanks for all the work you're doing everyday to make biblestudy better :)

A few months ago, you told me a new bootstrap based and mobile friendly version would be released soon. 
Do you have any idea about when?

Thanks and once again, good job guys!
Blessings.

**Comment by tomfuller2** [comment]
We're in the testing and bug fix mode now so it'll be about a month I'm
thinking.

**Comment by koleror** [comment]
Wow that's even better than what I expected! 
Thanks! :)
