### ISSUE TITLE
Notice in Admin -> Check Assets and Fix assets

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#418]
Notice: Use of undefined constant JREQUEST_ALLOWRAW - assumed 'JREQUEST_ALLOWRAW' in ..\administrator\components\com_biblestudy\controllers\admin.php on line 242
Call Stack
Num Time	Memory	Function	Location
1	0.0007	150544	{main}( )	..\index.php:0
2	1.0619	2169384	JApplicationCms->execute( )	..\index.php:42
3	1.0619	2169472	JApplicationAdministrator->doExecute( )	..\cms.php:251
4	1.1595	3679712	JApplicationAdministrator->dispatch( )	..\administrator.php:159
5	1.1620	3727168	JComponentHelper::renderComponent( )	..\administrator.php:98
6	1.2018	4013248	JComponentHelper::executeComponent( )	..\helper.php:332
7	1.2025	4044616	require_once( '\administrator\components\com_biblestudy\biblestudy.php' )	..\helper.php:352
8	1.3113	4951760	JControllerLegacy->execute( )	..\biblestudy.php:46
9	1.3113	4951824	BiblestudyControllerAdmin->checkassets( )	..\legacy.php:730

**Comment by bcordis** [comment]
Fixed now.
