### ISSUE TITLE
Move to Core reCAPTCHA as are API is no longer supported.

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Joomla-Bible-Study#419]
We need to Move to Core Captcha system as are code i no longer supported and does not work.

**Comment by bcordis** [comment]
@tomfuller2 Let me know how soon we can code this in as it is broken in its state now.

**Comment by tomfuller2** [comment]
Yes. Let's move to core

**Comment by bcordis** [comment]
needs test

**Comment by bcordis** [comment]
@st-anton Test Please

**Comment by tomfuller2** [comment]
Is this done and ready to be closed? Has it been tested?

**Comment by st-anton** [comment]
Currently, I cannot test on a server, but on my local machine only. I do not see a Captcha, the local machine may be the reason.

Did you configure your template http://joomlaoregon.com/jbs/index.php/studies-list/sermon/792/1 to use reCaptcha? I do not see a Captcha there...

**Comment by bcordis** [comment]
Captcha is a plugin option.

**Comment by bcordis** [comment]
@st-anton This will us all Captcha plugins.
