### ISSUE TITLE
Podcast details: Fields look inconsistent, is this by design? 

### ISSUE THREAD

**Issue by mheiniger** [Joomla-Bible-Study/Joomla-Bible-Study#422]
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/blob/development/com_biblestudy/admin/models/forms/podcast.xml#L61-L83

My question: should the content of this two fields episodetitle and episodesubtitle be the same, or is it by design, that those two fields are different and have different options?

Examples:
When i look at episodetitle and episodesubtitle i see options that start with JBS_PDC_EPISODE_ and some that just start with JBS_PDC_.
It has even one that is called JBS_PDC_EPISODE_SCRIPTURE_ONLY and one JBS_PDC_SCRIPTURE_ONLY.

I am actually asking this, because on the output-side, those two fields are expected to have the same length of 7 options:
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/blob/development/com_biblestudy/site/lib/podcast.php#L259-L318

**Comment by bcordis** [comment]
This could be a old design bug and need a look at. @Tomfuller2 can you verify this?

**Comment by bcordis** [comment]
@mheiniger This could be also something with @st-anton needs to look at. Lets see if he has time.

**Comment by st-anton** [comment]
Yes, there are duplicate phrases but different keys. But the title and the subtitle has different selection, also in code. See \components\com_biblestudy\lib\podcast.php lines 182ff and lines 259ff.
I will clean up the language phrases.
btw: #441 opened

**Comment by bcordis** [comment]
@st-anton I will look into the case ASAP.

**Comment by st-anton** [comment]
@bcordis: Making the two cases identical is not that easy. The selection is partly different, partly indentical, but with different codes. This would mean adaption in the migration.

**Comment by st-anton** [comment]
Fixed phrases in #442 pull request

**Comment by st-anton** [comment]
I think, this can be closed. Agreed?
