### ISSUE TITLE
Backup system having errors in escaping to many times

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Joomla-Bible-Study#427]
The system is escaping to much and making the import look bad. We may need to redo the component to fix this for the j2.5 system so if they wish to export and import to other website it will not brake.

**Comment by bcordis** [comment]
@tomfuller2 Please verify this is fixed now.

**Comment by tomfuller2** [comment]
Having a hard time checking out and pulling the 8.x branch. Could you
possible zip up that package and send it to me so I can test?

**Comment by bcordis** [comment]
I'll do that ASAP.

**Comment by bcordis** [comment]
3e157a32085293220514b6d634d230c150eef1f7 see the change its only a small one.

**Comment by bcordis** [comment]
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/blob/8.x/build/packages/component/com_biblestudy.zip download this file. @tomfuller2

**Comment by tomfuller2** [comment]
Tried to install but it couldn't open the archive.

**Comment by bcordis** [comment]
@tomfuller2 please post commit that fixes this now.

**Comment by tomfuller2** [comment]
Fixed on Development branch https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/27b9c96a7c8b1fc234d2a26b2c45bb28c5e39f22
Fixed on 8.x branch: https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/4b8b9804122ac9a7013ec83fc799e296bfa62ac5
