### ISSUE TITLE
Install: \com_biblestudy\media\captcha“ does not exist

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#428]
Installer complains:
JInstaller: :Install: Die Datei „...\com_biblestudy\media\captcha“ existiert nicht.
I guess, this is a leftover in the xml installation file.

**Comment by st-anton** [comment]
... also some media folders are not copied:
fancybox, images, jss, less, player, plupload

**Comment by bcordis** [comment]
I will remove the ASAP. But don't know why the other folders did not copy.
