### ISSUE TITLE
Migrate BS808 to 900 after Joomla upgrade

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#429]
Fatal error: Class 'BibleStudyModelMigration' not found in ...\administrator\components\com_biblestudy\install\updates\9.0.0.php on line 328

**Comment by tomfuller2** [comment]
8.0.8 - upgrade to 9.0.0 with this error:

Notice: Use of undefined constant BIBLESTUDY_PATH_ADMIN_MODELS - assumed 'BIBLESTUDY_PATH_ADMIN_MODELS' in /home1/joomlaor/public_html/joomlaoregon_com/jbs/administrator/components/com_biblestudy/install/updates/9.0.0.php on line 10

Fatal error: Class 'BibleStudyModelMigration' not found in /home1/joomlaor/public_html/joomlaoregon_com/jbs/administrator/components/com_biblestudy/install/updates/9.0.0.php on line 329

This is line 10: JLoader::register('BibleStudyModelMigration', BIBLESTUDY_PATH_ADMIN_MODELS . '/migration.php');

Are the JBS paths loaded prior to this file being fired off?

**Comment by bcordis** [comment]
I thought so looking why not.

**Comment by bcordis** [comment]
@tomfuller2 retest now should work look like we did not have defines in the install script portion.

**Comment by bcordis** [comment]
@st-anton This should work now. Please test.

**Comment by st-anton** [comment]
This is fixed. Closed.

**Comment by tomfuller2** [comment]
Migration successful, but we'll need to work on getting rid of back slashes. 

<iframe width=\"560\" height=\"315\" src=\"//www.youtube.com/embed/mlH104lB1os\" frameborder=\"0\" allowfullscreen></iframe>

I think this has more to do with the backup.

**Comment by bcordis** [comment]
I fixed the backup problem with the new backup server script we will need
to release a 8.0.9 to have that fix in place there. Check the one now. I
got a clean backup sql now. we where over ex aping the db.

Thanks,
Brent Cordis
2406 Hermitage Park Dr.
Hermitage, TN 37076
615.429.6426

**Comment by tomfuller2** [comment]
I'll try it out. Is in the main branch?

**Comment by bcordis** [comment]
In the 8.x branch
