### ISSUE TITLE
Database differences: Migration scenario 1

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#431]
After migration scenarion 1. (install 8.0.8 on j2.5. Upgrade J2.5 to J3.x,. Install JBSM 9.x.)
the database is different compared to a bs900 new installation:
_bsms_mediafiles
`metadata` text NOT NULL,  <->   instead of `metadata` text,
`hits` int(10) DEFAULT NULL, <->  instead of   `hits` int(10) DEFAULT '0',
-missing-                                            <->    `player` int(2) DEFAULT NULL,
`checked_out` int(11) unsigned NOT NULL DEFAULT '0', <->    not present in new install
`checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', <->  not present in new install
KEY `idx_checkout` (`checked_out`), <->       not present in new install
KEY `idx_createdby` (`created_by`) <->      not present in new install

_bsms_order
    not present in new installation; table should be deleted

_bsms_servers
  `server_path` varchar(250) NOT NULL DEFAULT '', <->       not present in new install
  `server_type` char(5) NOT NULL DEFAULT 'local',  <->       not present in new install
  `ftp_username` char(255) NOT NULL, <->       not present in new install
  `media` text NOT NULL,   <->   instead of   `media` text,

_bsms_update
INSERT INTO `#__bsms_update` SET `id`='19',`version`='9.0.0';   <-> instead of ... `id`='17'

**Comment by st-anton** [comment]
The result is independent from the scenario.

**Comment by bcordis** [comment]
don't see server_type any where in the code. @st-anton  Can you retest now.

**Comment by bcordis** [comment]
@st-anton  are we in sync now? after the bug fix of #435?

**Comment by st-anton** [comment]
yes, #435 is fixed.

Still some leftovers:
_bsms_servers
  `server_type` char(5) NOT NULL DEFAULT 'local',
  `ftp_username` char(255) NOT NULL,
  `ftp_password` char(255) NOT NULL,
These are present in the 808 and need to be deleted.

Also the id's of _bsms_update are different
808 and 900 after migration of a 808:
INSERT INTO `#__bsms_update` SET `id`='1',`version`='7.0.0';
INSERT INTO `#__bsms_update` SET `id`='2',`version`='7.0.1';
INSERT INTO `#__bsms_update` SET `id`='3',`version`='7.0.1.1';
INSERT INTO `#__bsms_update` SET `id`='4',`version`='7.0.2';
INSERT INTO `#__bsms_update` SET `id`='5',`version`='7.0.3';
INSERT INTO `#__bsms_update` SET `id`='6',`version`='7.0.4';
INSERT INTO `#__bsms_update` SET `id`='7',`version`='7.1.0';
INSERT INTO `#__bsms_update` SET `id`='8',`version`='7.1.1';
INSERT INTO `#__bsms_update` SET `id`='9',`version`='7.1.2';
INSERT INTO `#__bsms_update` SET `id`='10',`version`='7.1.3';
INSERT INTO `#__bsms_update` SET `id`='11',`version`='8.0.0';
INSERT INTO `#__bsms_update` SET `id`='16',`version`='8.0.8';

900 new installation:
INSERT INTO `#__bsms_update` SET `id`='7',`version`='7.0.0';
INSERT INTO `#__bsms_update` SET `id`='8',`version`='7.0.1';
INSERT INTO `#__bsms_update` SET `id`='9',`version`='7.0.1.1';
INSERT INTO `#__bsms_update` SET `id`='10',`version`='7.0.2';
INSERT INTO `#__bsms_update` SET `id`='11',`version`='7.0.3';
INSERT INTO `#__bsms_update` SET `id`='12',`version`='7.0.4';
INSERT INTO `#__bsms_update` SET `id`='13',`version`='7.1.0';
INSERT INTO `#__bsms_update` SET `id`='14',`version`='7.1.1';
INSERT INTO `#__bsms_update` SET `id`='15',`version`='7.1.2';
INSERT INTO `#__bsms_update` SET `id`='16',`version`='7.1.3';
INSERT INTO `#__bsms_update` SET `id`='17',`version`='8.0.0';
INSERT INTO `#__bsms_update` SET `id`='18',`version`='8.0.8';
INSERT INTO `#__bsms_update` SET `id`='19',`version`='9.0.0';

**Comment by bcordis** [comment]
I'm going to try and look at this this weekend. Not sure what is why this not right now.

**Comment by st-anton** [comment]
Now it crashes with message "1060 Duplicate column name 'media' SQL=ALTER TABLE `fmnj33_bsms_servers` ADD COLUMN `params` TEXT NOT NULL;"
It seems, that the migration is called twice, because I see the database query twice; swapping around the sequence of database modifications in 9.0.0.sql will show up the other modification, that is the first mofification in sequence.

**Comment by bcordis** [comment]
Looks like there is more errors here. Can you put the steps you took to see it db it twice.

**Comment by st-anton** [comment]
Now it runs again, but still the same differences as in https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/431#issuecomment-70722090

**Comment by st-anton** [comment]
Now it crashes again with 1060 Duplicate column name 'params' SQL=-- Servers ALTER TABLE `fmnj33_bsms_servers` ADD COLUMN `params` TEXT NOT NULL; 
This is very curious; I see no obvious changes between the situation two days ago and today.
@bcordis : I still suspect, whether change in the the _bsms_update.id is a reason for this: In BS808 it was 1 to 11 and 16, now it is 7 to 19. But I manipulated the ids and it did not change anything.

**Comment by bcordis** [comment]
ID should not affect this thy are could be remove and nothing happen. I'll have to look at the 8.0.0 to 8.0.8 changes and make a SQL file that reflects that.

**Comment by bcordis** [comment]
@st-anton please retest now on deletion need to look into the problem why the params ALTER error.

**Comment by st-anton** [comment]
Yes it works again. (What did you do? I can't see a change in the code related to this?!?)

The only remaining issue is the leftover of 
_bsms_servers
server_type char(5) NOT NULL DEFAULT 'local',
ftp_username char(255) NOT NULL,
ftp_password char(255) NOT NULL,
I suggest to extend /admin/install/updates/9.0.0.php line 301
current: $columns = array('ftphost', 'ftpuser', 'ftppassword', 'ftpport', 'server_path', 'aws_key', 'aws_secret');
suggested: $columns = array('type', 'ftphost', 'ftpuser', 'ftppassword', 'ftpport', 'ftp_username', 'ftp_password', 'server_path', 'server_type', 'aws_key', 'aws_secret');

**Comment by st-anton** [comment]
Tested OK. Closed
