### ISSUE TITLE
Migration button: File cannot be imported

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#432]
Trying to import an bs808 db file by scenario 2. (backup db using JBSM backup. on fresh install of JBSM 9.x in j3.x migrate the backup file.)
The file can be selected, but pushing the submit button, the next screen says "Warning   No File Selected"
(In sequence, the database is not changed as well)

**Comment by bcordis** [comment]
I'm about ready to remove restore from that view. And put it all in migration do to they use the same system.

**Comment by bcordis** [comment]
05e5516ad6e22f84bdf32ce36a89a864c62ac025 Fixed this.
