### ISSUE TITLE
Migration scenario 4: Misleading message

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#433]
Migration scenario 4. (upload using to fresh install of j3.x and JBSM 9.x. using third party SQL software your old DB. Using the prefix under migration you migrate the old db to your new installation.)

The next screen says Migration working and finished, that's ok.
But the the message below says: 0 of 0 Processing: Finished
Nevertheless, the migration was done.

**Comment by st-anton** [comment]
Appears after every migration task: Obviously, the task has several steps (up to 5?), but in the end, only "0 of 0 Processing: Finished" is displayed. I think, this will confuse the user.

**Comment by bcordis** [comment]
I need to clean that up thanks.

**Comment by bcordis** [comment]
Please retest @st-anton

**Comment by st-anton** [comment]
Now it says: Processing finished.
Closed
