### ISSUE TITLE
Stick to the language file within the component / module / plugin?

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#438]
More and more, I'm convinced, that the possibility to store the language files within the component / module / plugin is not a good idea in general. And reading 
https://docs.joomla.org/Specification_of_language_files#Language_file_naming_conventions_and_precedence
says, that these files are local. And in fact, they are. Finder plugin (#406), postinstall messages (#404; still not solved) and other 'cross component usage' is not possible to handle.
What is the advantage of the local files? All languages are installed automaticly. Can this be done by the installer script as well? I remember a discussion, that the update of the local files is easier, but cannot find it.
At the moment, I see more disadvantages / workarounds than advantages.
I know, it is not the best time to start such a discussion. But maybe it is a good chance to clean up this.

**Comment by bcordis** [comment]
This was originally a move that Joomla was pushing allowing for better development and keeping the component language files out of the core. Plus it allowed for single language file usage.

**Comment by st-anton** [comment]
There's a great discussion: [http://issues.joomla.org/tracker/joomla-cms/5872#event-61189](http://issues.joomla.org/tracker/joomla-cms/5872#event-61189) and below.
My conclusion: There seems to be a trend to move to local language files. However: It is not fully supported (yet), neither by Joomla itself (plugin finder, component postinstall ...) nor by other components (ctransifex ...). So the 'cross component usage' currently works with the CORE language folder(s) only. We need to raise an issue in Joomla to change this.

**Comment by st-anton** [comment]
Raised a Joomla issue: [http://issues.joomla.org/tracker/joomla-cms/5900](http://issues.joomla.org/tracker/joomla-cms/5900)

**Comment by bcordis** [comment]
@st-anton I think I had made a work around for now for com_postinstsll view have you tested that as of lately?  The finder I have not looked into?

**Comment by st-anton** [comment]
I think, postinstall #399 can be closed soon :-)

**Comment by bcordis** [comment]
See fix now to biblestudy.xml

**Comment by bcordis** [comment]
@st-anton can we close this now?

**Comment by st-anton** [comment]
Yes, let's stay on the local language files. Currently, there are no big issues with this.
Closed.
