### ISSUE TITLE
Podcast episode subtitle: case 5 missing

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#441]
In the selection \components\com_biblestudy\lib\podcast.php lines lines 259ff the case 5 is missing

**Comment by bcordis** [comment]
@st-anton Looking at it look like there case added for 7 but case 7 is not used before so i'm changing it back to case 5.

**Comment by bcordis** [comment]
@st-anton Please test.

**Comment by mheiniger** [comment]
If you set that case to 5, you'll need to set the input field to 7 to 5 too: https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/blob/development/com_biblestudy/admin/models/forms/podcast.xml#L82, because its for JBS_CMN_CUSTOM

**Comment by bcordis** [comment]
OK fixed now.
