### ISSUE TITLE
Module frontend crashes

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#443]
Module crashes in the frontend with:
Fatal error: Cannot use object of type stdClass as array in ....\modules\mod_biblestudy\mod_biblestudy.php on line 38
Obviously the `$admin[0]->params` does not work

**Comment by bcordis** [comment]
@st-anton please test.

**Comment by st-anton** [comment]
Crashes not with
1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= AND (series.access IN (1,1,5) or study.series_id <= 0) AND study.access IN (1' at line 14 SQL=SELECT list.select,messageType.message_type AS message_type,teacher.teachername AS teachername, teacher.title as teachertitle, teacher.thumb, teacher.thumbh, teacher.thumbw,series.series_text, series.series_thumbnail, series.description as sdescription, series.access,book.bookname,GROUP_CONCAT(DISTINCT mediafile.id) as mids, SUM(mediafile.plays) AS totalplays, SUM(mediafile.downloads) as totaldownloads, ..........

**Comment by bcordis** [comment]
Ok I'm going to get This right to night. I'll take second look.

**Comment by bcordis** [comment]
@st-anton Test should be all fixed now.

**Comment by st-anton** [comment]
Does not crash anymore -> closed
