### ISSUE TITLE
JBS_ADM_RESET_ALIAS as button in database functions

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#444]
The reset of the alias feels a little bit strange in the tab 'administration settings'. It would be more intuitive to have this as a button in 'database functions'

**Comment by st-anton** [comment]
Didn't dig deeper in that but seems to be fairly easy in \administrator\components\com_biblestudy\views\admin\tmpl\edit.php

**Comment by bcordis** [comment]
@st-anton Let look at doing this in 9.0.0 version but in beta will let it ride.
