### ISSUE TITLE
Admin: Change of Player ends in 'empty' page

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#445]
In the Admin -> Player settings the Player of media may be changed. When changing e.g. internal player to direct link and press the submit button, the next page is somehow empty: The menue is still there, but the title below the menue is overwritten by a grey banner. There is no content.
![emptypageafterplayerchange](https://cloud.githubusercontent.com/assets/2517417/6036123/75aa35b4-ac40-11e4-92de-40563eac6fe0.png)

**Comment by tomfuller2** [comment]
This is probably also due to the change in moving player to params.

**Comment by bcordis** [comment]
@st-anton Test Please

**Comment by st-anton** [comment]
Test ok - closed
