### ISSUE TITLE
Change Player does not work(?)

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#446]
Changing the player in Admin -> Player setting seems to fail. After migration I get hundreds of media files with 'direct link' and 3 with 'internal player'. Changing the 'internal player' to 'direct link' has not effect. Still the same number of media with 'internal player'.
Maybe has to do with #445 ?

**Comment by tomfuller2** [comment]
Due to the changes Eugen made to the player system, this will have to be re-written.

**Comment by bcordis** [comment]
Closing duplicate problem of #445
