### ISSUE TITLE
Dropdown in templatecodes has wrong links

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#447]
In the Backend -TemplateCodes site, the individual templatecode gets a dropdown box when hover: Edit, publish archive and so on. In this page a wrong link is given (copy-paste error): It points to masse instead of templtecode.
\com_biblestudy\views\templatecodes\tmpl\default.php  lines 132 to 165
I think, 'message(s)' needs to be replaced by 'templatecode(s)'

I'm also curious about lines 121 to 123: Is it mediafiles that needs to be checked for permission?

**Comment by tomfuller2** [comment]
Fixed. https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/2b39c6d05097b20baaa59c6c79bd06f4cc4baec0
