### ISSUE TITLE
Site: Studies list failed

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#449]
It crashes with
`0 DateTime::__construct(): Failed to parse time string (Sonntag, 01. Februar 2015) at position 0 (S): The timezone could not be found in the database`

This is dependent on the template setting of the date format. Other date format gives:
`0 DateTime::__construct(): Failed to parse time string (1 Februar 2015) at position 5 (r): The timezone could not be found in the database`

**Comment by bcordis** [comment]
@st-anton can you dig into this a little deeper. I'm not able to reproduce this error.  Also give me steps to reproduce the error.

**Comment by st-anton** [comment]
Cannot reproduce with the current code - closed
