### ISSUE TITLE
Frontend: Administration pages need Joomla admin language file

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#450]
In the Frontend administration pages for studies and media files (and I guess for comments as well), a lot of Joomla language phrases like JTOOLBAR_PUBLISH are used. Please add
`$language = JFactory::getLanguage();`
`$language->load('', JPATH_ADMINISTRATOR, 'en-GB', true);`
`$language->load('', JPATH_ADMINISTRATOR, null, true);`
in the specific views, e.g. site\views\messagelist\view.html.php  line 108

**Comment by st-anton** [comment]
I guess, this is needed in the administration pages of studies edit, media files edit and comments edit as well; not tested.

**Comment by bcordis** [comment]
@st-anton can you add this to your language load scripts?

**Comment by bcordis** [comment]
@st-anton This should be fixed now. Please re-test I updated paths to us are defines.

**Comment by st-anton** [comment]
Test ok -> Closed
