### ISSUE TITLE
Frontend new / edit study: Calendar popup does not work

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#455]
Tab 'Publishing options' -> Study date
The date can be entered manually, but the mini calender to select a date does not pop up.

**Comment by st-anton** [comment]
Does not work for start publishing and finish publishing as well

**Comment by bcordis** [comment]
Fixed with Commit d230c0c644648b1e747cab97f32c21375ee57749 adding in JQuery
