### ISSUE TITLE
Frontend new / edit study: Save shows curious message

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#460]
When saving a new study, the next page is the studies list with a curious message:
**Message**
**No Item Selected**     <<--- What does this mean?
**Item successfully submitted.**

**Comment by bcordis** [comment]
@st-anton Can you retest and see if this is still present?

**Comment by bcordis** [comment]
@st-anton This should be fixed now.

**Comment by st-anton** [comment]
Test ok
