### ISSUE TITLE
Frontend media file list: What is 'select by' good for?

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#462]
There are three filter button: 'select by', 'select status' and 'ordering'.
Source: site\views\mediafilelist\tmpl\default.php  lines 52ff
What is the 'select by' good for? There's no selection to choose from. Can it be deleted?

**Comment by st-anton** [comment]
Also see #463

**Comment by bcordis** [comment]
Fixed missing info.
