### ISSUE TITLE
Frontend media file list: 'Ordering' has no effect

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#463]
There are three filter button: 'select by', 'select status' and 'ordering'.
Source: site\views\mediafilelist\tmpl\default.php lines 52ff
'Ordering' has some strange text: 'Ordering of the article within the category'
And pressing the button has no effect.
(Also see #462)

**Comment by bcordis** [comment]
@st-anton Test Please

**Comment by st-anton** [comment]
No change, still no effect

**Comment by st-anton** [comment]
Hint: In the Comments Admin, the dropdown menue does have an effect.

**Comment by bcordis** [comment]
Ok I'll do some more digging.
