### ISSUE TITLE
Frontend Admin comments crashes

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#466]
Several notices and a fatal error:
Notice: Undefined property: JObject::$template in ...\components\com_biblestudy\views\commentlist\view.html.php on line 66
Notice: Trying to get property of non-object in ...\com_biblestudy\views\commentlist\view.html.php on line 66
Notice: Undefined property: JObject::$params in ...\com_biblestudy\views\commentlist\tmpl\default.php on line 19
Fatal error: Call to a member function get() on a non-object in ...\administrator\components\com_biblestudy\helpers\html\biblestudy.php on line 75
Call stack shortened:
14	1.3883	5340400	include( '...\views\commentlist\tmpl\default.php' )	..\legacy.php:663
15	1.4498	5861752	JHtml::_( )	..\default.php:19
16	1.4499	5862520	JHtml::call( )	..\html.php:140
17	1.4499	5862920	call_user_func_array ( )	..\html.php:238
18	1.4499	5863136	JHtmlBiblestudy::loadCss( )	..\html.php:238

**Comment by bcordis** [comment]
@st-anton Test Please

**Comment by st-anton** [comment]
Test OK, Closed
