### ISSUE TITLE
Frontend and backend: mediafile.xml looks very different

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#467]
The both files 
\administrator\components\com_biblestudy\models\forms\mediafile.xml
site\components\com_biblestudy\models\forms\mediafile.xml
looks very different. The files 'message.xml' and 'comment.xml' are very similar.
Is this ok?

**Comment by bcordis** [comment]
Right now @genu  was going to fix this but not sure if he will be able to.

I may have to start on @genu work soon if you dos not respond soon.

**Comment by bcordis** [comment]
@st-anton Fixed.
