### ISSUE TITLE
Data migration of plays, downloads, podcast

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#469]
I notice in a migrated db from 8.x to 9.x that 

1. No podcasts are migrated - they are all -1. 
2. Downloads and plays are spread across three different fields with different values.

From params: "hits":25,"downloads":"41" (this value is repeated in every record!)
From Metadata: {"hits":11,"downloads":"0"}
From downloads: 0
From plays: 13 (I think this one is correct)
So which is correct and which is used?

**Comment by st-anton** [comment]
I have two podcasts during migration (from 8.0.0): Both podcasts are migrated, both have a valid ID, everything is fine in my db.
Also the database _bsms_mediafiles->podcast_id is fine.

**Comment by bcordis** [comment]
@tomfuller2 The Downloads and plays? Can you point me to what you are referring to or a record.  Is this under the media table or somewhere else?

**Comment by tomfuller2** [comment]
It is in a mediafile record. Let's not worry about this right now. I just
noticed multiple entries in different fields for the same thing. It may be
that we are reporting it correctly.

**Comment by bcordis** [comment]
@tomfuller2 we do need to make it better for states and make sure we are calculating this right I'll look and make sure we are good.

**Comment by bcordis** [comment]
@tomfuller2 I think this is fixed but need you to verify so we can close this.

**Comment by tomfuller2** [comment]
I'll have to retest a migration. Will do it as soon as I can but extremely
busy right now!

**Comment by st-anton** [comment]
I did a migration from 8.0.0 and I cannot find a problem:
...`study_id`='265',`server_id`='5',`podcast_id`='2,1',`metadata`='{}',`ordering`='0',`createdate`='2015-05-31 07:04:08',`hits`='0',`published`='1',`comment`='',`downloads`='0',`plays`='2',`params`='{...shortened
So: No double entry, metadata is empty, numbers are correct.
-> can be closed
