### ISSUE TITLE
Media file with no server lacks params in new server record

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#470]
Case: 8.x db with no server selected (because it uses embed code)
Result after upgrade from 8.x to 9.x - server record titled defualt (a mispelling that needs to be corrected) and no params are created. This causes a notice of:
Notice: Undefined property: stdClass::$path in /home1/joomlaor/public_html/joomlaoregon_com/jbs/components/com_biblestudy/helpers/media.php on line 708.
708 is: if ($params->path) - this is coming from #__bsms_servers->params.
Not a fatal error but should be corrected. 
Not sure what line in install/updates/9.0.0.php this is coming from Brent.

**Comment by bcordis** [comment]
@tomfuller2 Right now i'm not seeing the usage of $params->path as we use $params->filename

Can you explain how you came about this?

**Comment by tomfuller2** [comment]
It's taken from servers in the query then merged

**Comment by bcordis** [comment]
@tomfuller2 Yes we change path to filename when we converted to params and doing that it also has includes the folder name.

I don't see path used after the migration. So I don't see the use after the migration happening.

**Comment by st-anton** [comment]
Another case: I have 3 servers in the 800. After migration I have 4 servers; the last one is the 'defualt', this is published=1. Does this make sense? I don't think so.

**Comment by bcordis** [comment]
Default us used for media that did not have servers set to them before. So 4 servers would be correct.

**Comment by bcordis** [comment]
@tomfuller2 @st-anton Ok found there error now I'm making a fix for it.

**Comment by bcordis** [comment]
@tomfuller2 Please Test
