### ISSUE TITLE
Frontend Admin comments: edit crashes

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#472]
URL is: http://localhost/j33_test/index.php/kommentare-admin/2?task=comment.edit
Message:
0 **Invalid Controller: name='comment', format=''**

**Comment by bcordis** [comment]
@st-anton Can you explain what link you clicked on to get this error.

**Comment by bcordis** [comment]
@st-anton Try retesting.

**Comment by st-anton** [comment]
Test ok -> Closed
