### ISSUE TITLE
Frontend Study List layout: Most of the filter dropdown boxes are missing

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#476]
I enabled all of the filter boxes in the template but only 'Number of items' and 'ordering' is displayed. No 'Go' button, no filter for years, locations, sereis and so on.

**Comment by bcordis** [comment]
@tomfuller2 can you look into this.

**Comment by tomfuller2** [comment]
Fixed. The $dropdowns variable was reset partway down the page. https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/6811ea5daf6691ebd71ef549f5d79b1f69110c56

**Comment by st-anton** [comment]
Still missing:
Books, Teacher, Series, Message Type

**Comment by st-anton** [comment]
If a selection is set to 'show unless filtered', the selection box is always hidden. Setting it to 'show always' it does what it says.

**Comment by tomfuller2** [comment]
This is fixed now. Please test. There was a missing "m" on all of the $filter varables.
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/ea78d250447be2593d09638697cbaa159db61992

**Comment by st-anton** [comment]
Test ok, works well.
