### ISSUE TITLE
Export Template crashes

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#478]
Fatal error: Call to undefined method JBSMRestore::output_file() in \administrator\components\com_biblestudy\controllers\templates.php on line 358

**Comment by bcordis** [comment]
@st-anton Retest now. Should work right.

**Comment by st-anton** [comment]
Export and import are working. But I have to look deeper in the db, as some entries may be changed.

**Comment by st-anton** [comment]
Test ok -> Closed
