### ISSUE TITLE
Activating podcast plugin shows a lot of warnings

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#479]
Right after new installation of component and podcast plugin, I activated the podcast plugin.
Several warnings appeared:
Warning: getimagesize(http://localhost/j33_test/www.mywebsite.com/myimage.jpg): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in \components\com_biblestudy\lib\podcast.php on line 497
Notice: Undefined property: stdClass::$params in \components\com_biblestudy\lib\podcast.php on line 149
Notice: Undefined property: stdClass::$size in \components\com_biblestudy\lib\podcast.php on line 182
Notice: Undefined property: stdClass::$linktype in \components\com_biblestudy\lib\podcast.php on line 344
Notice: Undefined property: stdClass::$link in \components\com_biblestudy\lib\podcast.php on line 348
Notice: Undefined property: stdClass::$mimetype in \components\com_biblestudy\lib\podcast.php on line 405

**Comment by st-anton** [comment]
Does not happen, if deactivating and activating again

**Comment by bcordis** [comment]
I'll put this into are debug list as we need to make sure it works. It may not be fixed by bate1.

**Comment by st-anton** [comment]
Now I know, why it happens only 'once': This messages are written, when the podcast xml file is written. Naturally it may happen any time in fronend or backend. This seems to me quite critical.

**Comment by bcordis** [comment]
@st-anton moving to hi priority and will debug.

**Comment by bcordis** [comment]
Fixed.
