### ISSUE TITLE
Plugin language phrases are lost

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#480]
Obviously I made a mistake during the delivery / pull request on 2014-12-29 or 2015-01-04.
I try to resptore them out of my backups

**Comment by st-anton** [comment]
Should be fixed by #477; I will test after merge

**Comment by bcordis** [comment]
@st-anton Test now merge completed.

**Comment by st-anton** [comment]
Test ok -> closed
