### ISSUE TITLE
Backup done by backup plugin crashes

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#481]
Enabling the backup plugin starts a backup. This crashes with:
Fatal error: Class 'JBSMDbHelper' not found in \administrator\components\com_biblestudy\lib\backup.php on line 52
Please merge #477 first, because there is another fix of the backup plugin.

**Comment by bcordis** [comment]
@st-anton Please retest now.

**Comment by st-anton** [comment]
Does not crash anymore -> Closed
