### ISSUE TITLE
Adjusting db of installation and migration

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#483]
Currently the sql db of #__bsms_mediafiles, #__bsms_servers and #__bsms_topics have same content after installation and migration, but the columns have different order. This makes it hard to compare and may make problems in the future.
I would like to see the columns in the same order. I would do it, if you aggree.

**Comment by bcordis** [comment]
@st-anton That would be best. Do you need me to look into this?

**Comment by st-anton** [comment]
I added a new pull request, but the new pull request was merged with the former one #477. Can you please merge it and have a look?

**Comment by st-anton** [comment]
Tested with 8.0.8, 8.0.0, 7.1.2: OK
Closed
