### ISSUE TITLE
Podcast: Several fields have additional ![CDATA[ prefix

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#486]
Example:
`<itunes:author><![CDATA[Andreas Engelbert]]></itunes:author>`
`<dc:creator><![CDATA[Andreas Engelbert]]></dc:creator>`

Comparison with BibleStudy 8.0.0:
`<itunes:author>Andreas Engelbert</itunes:author>`
`<dc:creator>Andreas Engelbert</dc:creator>`

(Maybe this has something to do with #479?)

**Comment by bcordis** [comment]
No this is not related. and not a bug. This is to handle html in the strings.
