### ISSUE TITLE
Menue entry single study layout: can be set up without study

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#488]
In the menue entry single teacher a teacher is mandatory. This is not the case in the single study layout.
Subsequently the Frontend page crashes:
1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY c.comment_date asc' at line 4 SQL=SELECT c.* FROM fmnj33_bsms_comments AS c WHERE c.published = 1 AND c.study_id = ORDER BY c.comment_date asc ....

**Comment by tomfuller2** [comment]
Added required to study. https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/b75cfa1b8fcf7f2c9a256f10034371fdd8b8b687
