### ISSUE TITLE
Please review language files; some phrases are missing

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#489]
I found some new phrases (delivered with #477); please search for `"JBS_` and enter the english text

**Comment by bcordis** [comment]
@st-anton Is there a way to nerrow this down. Right now i'm not seeing the missing frases?

**Comment by st-anton** [comment]
These are:
JBS_MED_ADD_THIRD_PARTY_URL
JBS_MED_ENTER_SERVER
JBS_MED_FIELDS_INVALID
JBS_MED_FILE_NO_UPLOADED_AWS
JBS_MED_SURE_OVERWRITE_DETAILS
JBS_TPL_RESPONSIVE
JBS_TPL_RESPONSIVE_DESC
JBS_TPL_SHARELABEL
JBS_TPL_SHARELABEL_DESC
