### ISSUE TITLE
Module does not show a studies list

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#491]
I'm not sure, whether I missed a setting, but I was not able to set up a studies list. The only thing I see is the header and the 'More Bible Studies' link.

**Comment by tomfuller2** [comment]
Did you go into the template and make some settings? It's a different setup
than prior versions.

**Comment by st-anton** [comment]
Yes, I set up the settings in the module, so I expect to see the studies list. And yes, the template was set up to show a studies list as well. But: What influence should the template have, as all the settings are twice, one time in the template and a second time in the module again?

**Comment by bcordis** [comment]
Yes the model only should override the display of the template option. Need to work on that a little better.

**Comment by bcordis** [comment]
@tomfuller2 I need you to Look over the overight settings. We also need to get the defaults in line.

I think we need to make this streamline.

**Comment by tomfuller2** [comment]
Sorry - you need to make the settings in the module, not the template.
I also fixed a coding issue where a custom template file would not use pagebuilder and thus some fields would not display correctl. https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/07e1ffb6e817f2737d6c87d8e9ba84bb6f4144f8
you set what shows up on the different rows in the settings in the module. Like other Joomla modules.
