### ISSUE TITLE
#__bsms_podcast->linktype inserted in migration, but not in installation

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#492]
With the commit in the file com_biblestudy/admin/install/sql/updates/mysql/9.0.0.sql you added a column `linktype`. This is missing in the installation (and the install defaults).

**Comment by bcordis** [comment]
You are correct I'll update them ASAP.

**Comment by bcordis** [comment]
@st-anton Fixed
