### ISSUE TITLE
Backend new Media: next page is corrupted

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#497]
The next page after editing a media file  (save of abort) is corrupted: The top banner is hidden / overwritten, the page is empty except the menu

**Comment by st-anton** [comment]
If the item is saved, the next page is fine. If canceled, the next page is corrupted.

**Comment by tomfuller2** [comment]
I can confirm this behavior. There are no error messages, only part of the header displays. 
What's happening is that the "Close" button's url is pointing to the edit link, not the list link. 
I tried removing parts of the submit button javascript in the mediafile/edit.php but to no avail.

**Comment by bcordis** [comment]
Fixed.

**Comment by st-anton** [comment]
Test ok -> closed
