### ISSUE TITLE
Backend new media: selecting server clears field of study and date

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#498]
When selecting the server, a new set of tabs appear and the fields of study and date are cleared. Naturally, the save fails because of empty mandatory fields.

**Comment by tomfuller2** [comment]
When editing a study in the backend, if you try to add a new media file, the study and date information do not follow to the window that's opened for the media file.

**Comment by tomfuller2** [comment]
Also, if you edit a media file from a study - then save it without making changes, the server is not saved. Some corruption is happening.

**Comment by bcordis** [comment]
@tomfuller2 can we meet on this and see what all needs to be fixed to make it work. Right now i'm having to work through the code and see where this is broken at.

**Comment by bcordis** [comment]
@st-anton This is a normal function of joomla if you did not save the media before selecting a new server. I have also fixed the new media creation from a message to have a date and message link. I do think there is a better way to select servers.

**Comment by tomfuller2** [comment]
The problem is I have no idea how to fix this. This is part of the new
system you and Eugen developed.

**Comment by bcordis** [comment]
@st-anton @tomfuller2 This should be fixed now.

**Comment by st-anton** [comment]
Right direction, but still curious behaviour (tested in backend only):
Obviously, the last server I saved in the server page is used as type (in my case: legacy server). So I see all tabs and can fill in all the fileds for legacy server. That fits if I have only one server.
But: switching over to another type of server has no effect: Tabs are not changing. Also the other server is not saved with the media. It always returns to the 'default' server.

Now also two notices appear, when starting a new media:
Notice: Undefined property: stdClass::$study_id in ...\administrator\components\com_biblestudy\views\mediafile\tmpl\edit.php on line 69
Notice: Undefined property: stdClass::$createdate in ...\administrator\components\com_biblestudy\views\mediafile\tmpl\edit.php on line 77

**Comment by bcordis** [comment]
Ok I'll do some more checking but I'm close now

**Comment by bcordis** [comment]
@st-anton ok now it saves right but need to find a way to trigger save on change.  It still requires that date and study_id have to be selected.

**Comment by bcordis** [comment]
@st-anton please test.

**Comment by st-anton** [comment]
`Select a study` opens the popup for servers.
The additional tabs do not appear anymore. So none of the parameters can be filled in.
Popup Box: Unpublished servers are still selectable; this is misleading to the user. At least the published / unpublished state needs to be displayed.

**Comment by bcordis** [comment]
@st-anton so what view is not showing study any more?

**Comment by bcordis** [comment]
Found the error.

**Comment by bcordis** [comment]
@st-anton retest. This now is fixed. found the error. and added some better search functions.

**Comment by st-anton** [comment]
Study item and study date now persist.
Still no further tabs appear, as the trigger on change does not work.
