### ISSUE TITLE
Addon language cannot be added

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#500]
In admin adding new server. If you choose ftp or Amazon you get this error:
 
"Addon language could not be loaded"

**Comment by st-anton** [comment]
Naturally: There is no language file at all to load. Maybe you missed to add them to Git?
Legacy and local bring with them a language file.

**Comment by st-anton** [comment]
@tomfuller2 Should we add a dummy file to be loaded? Or do you have some phrases to add here?
As mentioned above, legacy and local bring with them a language file. Amazon and ftp currently have no language file.

**Comment by bcordis** [comment]
@tomfuller2 @st-anton I have added a dummy Language files to them for now. will work on them latter.
