### ISSUE TITLE
Single Series Display shows all studies of ANY serie

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#501]

**Comment by st-anton** [comment]
Same happens if you klick on a serie in the landing page.

**Comment by tomfuller2** [comment]
I can confirm this. Probably a problem with the model

**Comment by tomfuller2** [comment]
It is a problem with the sermons model. In lines 447 and beyond we capture the state of the filter but it is not passed on to the model in lines 631 and beyond. It seems maybe this was supposed to take place in lines 620 but this has been changed. Will need to do some investigation.

**Comment by tomfuller2** [comment]
Basically none of the filters work now that are &filter_series=5 etc.

**Comment by tomfuller2** [comment]
This is fixed. Needed a paren around a where query in the sermons model at line 598. 
$query->where('(series.published = 1 or study.series_id <= 0)');
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/b5dfad810bbb4e37297ea3f2ff9a4c14de0a433f

**Comment by st-anton** [comment]
...but it does not work. Still all studies of all series, regardless of opening the 'Single Series Display' out of a menue item or click on the link of a serie in the series list display.

**Comment by tomfuller2** [comment]
Fixed this - it was a problem with the query again. Not sure why I didn't fix this before.
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/494d90b13f395ccb6fc27c3a6a6ae70abd897b26
Please test.

**Comment by st-anton** [comment]
Test ok -> closed
