### ISSUE TITLE
Series List Display filter gets a notice if result is empty

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#503]
If the filter result is empty (no serie found for this combination of selections), an Joomla notice is displayed:
Notice: Undefined offset: 0 in ...\components\com_biblestudy\lib\listing.php on line 342

**Comment by tomfuller2** [comment]
Try pulling now. I added a test to see if $items is an object when using headers in a series list.

**Comment by st-anton** [comment]
Test OK -> closed
