### ISSUE TITLE
Single Series Display: Filter for popular does not use 'Go' button

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#504]
The filter for popular studies is the only one that does not use the 'Go' button, even if it is defined to use it.
All the other filter dorp downs use the 'Go' button.

**Comment by st-anton** [comment]
Bad news: They use the 'Go' button, but they do not have any effect.

**Comment by st-anton** [comment]
Same situation at the study list display: Filter have no effect, popular does not use Go button.

**Comment by tomfuller2** [comment]
That's by design.

**Comment by st-anton** [comment]
In earlier time; I tested without JavaScript, so I expected, that this behaviour will not work. But the actual version of Firefox does not have any setting to switch off JS. So this is no more 'state of the art'.
--> closed
