### ISSUE TITLE
Single Serie Display: What is the difference of the two pages?

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#505]
When selecting a menue 'single serie', the given number of studies is displayd, but no filter selection. At the end there is a button 'show all studies from this serie'. This page shows the same studies (with different pagination) including the filter selection.
Can this two pages be united to one page?

**Comment by tomfuller2** [comment]
It appears to work correctly for me. I click on a series and it shows only the number I've specified. Then when I click on "Show all studies" it goes to a study list with all of the studies available for that series. Can you recheck Anton?
