### ISSUE TITLE
Frontend new / edit media: No selection of the study

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#506]
There is a field, but there is no button with a modal popup to select a study.

**Comment by st-anton** [comment]
Currently, nearly all of the tabs show no input field. The tabs are simply empty. I remember a bug in the past, that the tabs were empty, if the server was not selected. But now, the server is selected (legacy type) and the tabs are empty.

**Comment by bcordis** [comment]
@st-anton Fixed please test. fadfb9137715ee7536162bf7826282197752e86b

**Comment by st-anton** [comment]
Study selection is fixed -> closed
Server stuff is still open -> This needs to be fixed
