### ISSUE TITLE
Frontend new / edit media: Notices

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#507]
Notice: Undefined property: JObject::$server in ...\components\com_biblestudy\views\mediafileform\tmpl\edit.php on line 42
Notice: Undefined property: JObject::$path in ...\components\com_biblestudy\views\mediafileform\tmpl\edit.php on line 56

**Comment by st-anton** [comment]
This may lead to another effect: nearly all of the tabs have empty content / no input fields.

**Comment by st-anton** [comment]
Note: My default server is a legacy server. But this is not taken in. Moreover, if I select the server, the inputs of date and study is dropped (same happens in the backend).

**Comment by bcordis** [comment]
Fixed fadfb9137715ee7536162bf7826282197752e86b @st-anton

**Comment by st-anton** [comment]
Test ok -> Closed
