### ISSUE TITLE
Frontend new / edit study: Wrong link at selection of the user?

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#508]
The edit of the study allows the selection of the user ('submitted by'), saying `select a user`. This link leads to the own profile, but there is no selection of users.

**Comment by tomfuller2** [comment]
On my test site I made a new user - then was able to see my user and the new one when selecting "submitted by" so I'm not seeing this bug.

**Comment by st-anton** [comment]
I see the following popup:
![user](https://cloud.githubusercontent.com/assets/2517417/6771695/781078d4-d0e6-11e4-8694-bcaffffba4c8.png)
Is this the intended way it should work? I expected a possibility to select another user, not myself.

**Comment by tomfuller2** [comment]
Not sure. I wonder why it's a selection if you can't switch users?

The field in the model/form is this:

<field name="user_id" type="user" label="JBS_CMN_SUBMITTED_BY"
class="span12 small"/>

**Comment by bcordis** [comment]
You should be able to select different user. I have tested this and it work as expected.

**Comment by bcordis** [comment]
@tomfuller2 @st-anton Please retest.

**Comment by st-anton** [comment]
Maybe we look at different fields:
- Frontend `Submitted by`showing the current user only. See image above.
- Backend `Submitted by` showing a selection of all Joomla users. Anybody may be selected.
- Frontend and Backend: `Modified by` allows no selection, but the field says `Select a user'. This is confusing.

**Comment by bcordis** [comment]
Ok that is a bug will look into the difference.

**Comment by st-anton** [comment]
Joomla documentation mention nothing about a difference between admin and site.
Maybe this helps: The link to call the modal box is:
admin: http://localhost/j34_test/administrator/index.php?option=com_users&view=users&layout=modal&tmpl=component&field=jform_user_id
site: http://localhost/j34_test/index.php/component/users/users?layout=modal&tmpl=component&field=jform_user_id
If I fake the link in the site (Firebug plugin of Firefox allows this), the correct modal box comes up.

**Comment by bcordis** [comment]
@st-anton @tomfuller2 Right now there is the same call to the core User section and no difference from backen to front. Closing for now.
