### ISSUE TITLE
Frontend Single Study Layout: Too much </div>

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#510]

**Comment by tomfuller2** [comment]
I'm not seeing this. If you go to my test site it appears to be working okay:
http://joomlaoregon.com/jbs/index.php/studies-list/sermon/940-hostility-towards-god/1 
How are you seeing that there are too many divs?

**Comment by st-anton** [comment]
I found another one: Series List display. You will find the menue to be below the list instead of the right side.
site\com_biblestudy\views\seriesdisplays\tmpl\default_main.php  line 103
`		<input name="boxchecked" value="0" type="hidden">`
`		<input name="controller" value="seriesdisplays" type="hidden">`
`</div>`   <-- remove this
`</form>`
`</div> <!-- end of container-fluid div -->`

I will debug furthermore on the single study display. It seems to have to do with comments.

**Comment by st-anton** [comment]
I got it. Each displayed comment troubles the sequence of div.
site\com_biblestudy\views\seriesdisplays\tmpl\default_main.php line 103 and 104 should be removed. These two lines add two `</div>` for each comment.
(Note: The comment form does not make problems).

I will add these changes. Also found a superfluous <td>.

**Comment by tomfuller2** [comment]
Are you going to fix this in the code?

**Comment by st-anton** [comment]
I did a pull request; git added this to the #499

**Comment by tomfuller2** [comment]
Closed?

**Comment by st-anton** [comment]
When pull request #499 is merged, we can close this.

**Comment by st-anton** [comment]
Test ok -> closed
