### ISSUE TITLE
Frontend Landing page: Some books appear twice

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#511]
Note for me: Matthew and 1John

**Comment by tomfuller2** [comment]
Check your book listing in the db. 
http://joomlaoregon.com/jbs/index.php/landing-page mine looks okay

**Comment by st-anton** [comment]
It has to do with the access level. Example: One study is 'public', the other is 'guest'. If both use the same book, it appears twice.
Curious: I have additional access levels (friends, member ...), and it does not happen there.

**Comment by st-anton** [comment]
Verified: The book of a study with access level 'guest' appears on the landing list, even if nobody is locked in (i.e. public access of the page).
If the study is defined for 'member' - a self defined additional access level - the book appears only, if a member is locked in.

**Comment by tomfuller2** [comment]
I think I fixed this using a GROUP command in the query. @st-anton can you check?
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/fa96d588b2b0e3c2098aa36f0d3cc23de4af8b1e

**Comment by st-anton** [comment]
Works fine -> closed
