### ISSUE TITLE
Classclose of listing gives wrong code

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#512]
\components\com_biblestudy\lib\listing.php  line 1569
If class is e.g. `<p` then classclose will get `</<p>`
Result is e.g. `<div class=""><p >1/25/2015</<p></div>`

**Comment by tomfuller2** [comment]
Can you show this happening? On my test site: 
http://joomlaoregon.com/jbs/index.php/studies-list 
If you look at the html, the class codes are correct.

**Comment by st-anton** [comment]
Yes, it does happen. Please see line 242 of the delievered html, e.g. :
`<div class=""><p >Colossians 1:21-29</<p></div>`
(Btw: Is it possible to add a new line at the end of a study? A line with 15000 characters is hard to read :-))

**Comment by tomfuller2** [comment]
Do you have a public server where you can show me this? I'm trying to figure out what's causing it because I can't replicate the behavior.

**Comment by st-anton** [comment]
Sorry, for not being clear: It happens in your page (URL above) line 242 of the delivered html.

**Comment by tomfuller2** [comment]
I'm still not seeing it. 
On my studies list, for instance, this display: 1/18/2015 from the first listed study
has this associated code: <h5>1/18/2015</h5>

**Comment by st-anton** [comment]
![classcode](https://cloud.githubusercontent.com/assets/2517417/6645973/d781b094-c9c0-11e4-8b0d-c0d364ba1afd.png)

**Comment by tomfuller2** [comment]
That's weird - because using FireBug the html shows as: <p>Colossians 1:21-29</p> using the FireFox Browser.
But in Safari it shows up as <p >Colossians 1:21-29</<p> as you point out. I'll take another look at the code.

**Comment by tomfuller2** [comment]
Fixed https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/844f7044876bf7a9c5af5657399b0abbe8be5a7a

**Comment by st-anton** [comment]
Test ok
