### ISSUE TITLE
Image width and height are double

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#513]
I found duplicate width and height tags:
`<img src="whatever/com_biblestudy/images/download.png" alt="Download" width="24" height="24" width="24" height="24">`
This is caused by ...\components\com_biblestudy\helpers\media.php line 89 and 96.
I think the extension in line 97 is not needed.

**Comment by tomfuller2** [comment]
Do you have some html that shows this happening on a page?

**Comment by st-anton** [comment]
Ah, sorry, the comment was formatted wrong. Please find it above.

**Comment by st-anton** [comment]
I remembered a very helpful site to check the html elements:
http://validator.w3.org/
There you see on your page the double width and height elements.

**Comment by st-anton** [comment]
I got it:
libraries/joomla/image/image.php line 136 gets the imagesize:
`'width' => $info[0],  is   24`
`'height' => $info[1],   is   24`
`'attributes' => $info[3],  is   width="24" height="24"`
with
site/heplers/media.php line 96, both the `attributes` as well as the `width`and the `height` is put in.

So either is obsolete.

**Comment by bcordis** [comment]
@st-anton @tomfuller2 retest.

**Comment by st-anton** [comment]
Fixed -> closed
