### ISSUE TITLE
Frontend: all admin pages crash

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#514]
This happens regardless of being guest or super user.

Admin comments:
Notice: Trying to get property of non-object in ...\components\com_biblestudy\models\commentlist.php on line 64
Fatal error: Call to a member function merge() on a non-object in ...\components\com_biblestudy\models\commentlist.php on line 64

Admin media:
Notice: Trying to get property of non-object in ...\components\com_biblestudy\models\mediafilelist.php on line 52
Fatal error: Call to a member function merge() on a non-object in ...\components\com_biblestudy\models\mediafilelist.php on line 52

Admin study:
Notice: Trying to get property of non-object in ...\components\com_biblestudy\models\messagelist.php on line 49
Fatal error: Call to a member function merge() on a non-object in ...\components\com_biblestudy\models\messagelist.php on line 49

**Comment by tomfuller2** [comment]
I added a frontend menu for message ADMIN and got no errors.

**Comment by st-anton** [comment]
It hat to do with the template - but I'm not sure.
In ...\components\com_biblestudy\models\commentlist.php on line 61 it tries to get the template with id=1. But in my case, I unpublished the template with id=1, so the return value is undefined instead of a template.
Which template should be used? Where can I define it?

**Comment by st-anton** [comment]
In the menue setup, there is a field where the template is selected. I selected one of the published templates - naturally, the unpublished template is not in the list. But: Obviously, the selection has no effect, the template with id=1 is always used.

**Comment by tomfuller2** [comment]
So actually there are no user settings - this view doesn't use the JBS template I don't think. So I'm going to remove the template choice.

**Comment by tomfuller2** [comment]
Works now for me. Removed the template choice from the Admin of studies on front end.
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/baf762ff0a3dd0dcc7be0aaf81da09d8d02e41c9

**Comment by st-anton** [comment]
No improvement.
Why does the page use a template out of the templates list? In the Backend the template is not used to list studies, media, comments. I think, the same should be in the frontend. But the template (id=1) may be selected accidentally.

**Comment by tomfuller2** [comment]
When you say "no improvement" - what do you mean? Are they still crashing?

**Comment by st-anton** [comment]
Yes, if the template with id=0 is unpublished.

**Comment by tomfuller2** [comment]
Did you manually delete the default template? A normal user would not be
able to do that

**Comment by st-anton** [comment]
![unpublish_templates](https://cloud.githubusercontent.com/assets/2517417/6905514/b6207d3e-d728-11e4-98e8-85840803ff5f.png)

**Comment by bcordis** [comment]
@tomfuller2 @st-anton look like they can right now so i'm putting in a stop to it. will post a fix asap. but this should not happen any way. making sure even if that is unpublished it still works.

**Comment by bcordis** [comment]
@st-anton @tomfuller2 Please retest.

**Comment by st-anton** [comment]
Work on the templates **list** page.

But: I succeeded to unpublish and even trash the item :-O
Opening the default template and change the status on the right hand menue from published to unpublished or trashed. Save. Now you have an unpublished or even trashed template.

**Comment by bcordis** [comment]
@st-anton fixed.

**Comment by st-anton** [comment]
Test ok
