### ISSUE TITLE
Frontend Single Teacher Display: Notice and Warning

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#515]
Warning: Invalid argument supplied for foreach() in ...\components\com_biblestudy\lib\listing.php on line 46
Warning: Invalid argument supplied for foreach() in ...\components\com_biblestudy\lib\listing.php on line 374

**Comment by tomfuller2** [comment]
Probably something to do with the studies associated with that teacher. I get no errors.

**Comment by tomfuller2** [comment]
Is this still an issue @st-anton ? No problems on my test site.

**Comment by st-anton** [comment]
Tried to get deeper into it:
\components\com_biblestudy\views\teacher\tmpl\default_main.php  line 24
$this->teacherstudies is uninitialised:
$this	BiblestudyViewTeacher	
	item	stdClass	
	contact	<Uninitialized>	
	state	JObject	
	params	Joomla\\Registry\\Registry	
	template	stdClass	
	teacherstudies	<Uninitialized>	
	print	
	document	JDocumentHTML	
	studies	<Uninitialized>	
	_name	teacher	
	_models	Array [1]	
	_basePath	.../components/com_biblestudy	
	_defaultModel	teacher	
	_layout	default	
	_layoutExt	php	
	_layoutTemplate	_	
	_path	Array [2]	
	_template	...\\components\\com_biblestudy\\views\\teacher\\tmpl\\default_main.php	
	_output	<Uninitialized>	
	_escape	htmlspecialchars	
	_charset	UTF-8	
	_errors	Array [0]	
	baseurl	/j33_test

**Comment by tomfuller2** [comment]
Fixed by putting in an IF statement in the default_main. Only shows studies if parameter is set.
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/d61afb376e0090cb0c500eb81eff1db772d2018e

**Comment by st-anton** [comment]
Test ok
