### ISSUE TITLE
Frontend Studies List Display (and Single Series Display): Filter does not work

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#516]
The content of the studies list does not change regardless of the filter selected. I tested with the 'Go' button, I did not tested the JS version of the filter.

**Comment by tomfuller2** [comment]
I'm not seeing this behavior. www.joomlaoregon.org/jbs - check out the studies list.

**Comment by st-anton** [comment]
It may have to do with the sequence of calls. And: Yes, the bahaviour on your site is a little bit different than my site, but in general the result is similar
I tried on your site, following sequence
1. None of the filters enables: studies starting in the year 2000, roughly 350 studies.
2. filtered for Year 2013: studies staring in the year 2007, roughly 300 studies
3. additionally filtered for teacher 'guest' or 'Steve Hopkins': no change from last result
4. Filter for Year 2000 instead of 2013: no change
I use Firefox 36.0.1

**Comment by tomfuller2** [comment]
I think this was fixed with the fix for the series links from the landing page. There was an error in the sermons model that retrieved every study regardless of the filter setting. I've tested it and now the filters seem to work.

**Comment by st-anton** [comment]
Test ok
