### ISSUE TITLE
Frontend Single Study Layout: Second scripture book name is identical with first

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#517]
Example: First scripture is genesis, second scripture is exodus.
Result:
3/10/2015  study test    Genesis 2    <= this is 1st scripture
                  teacher        Genesis 3    <= this is second scripture

**Comment by tomfuller2** [comment]
Fixed this in the sermons model. Had to add a new join to grab the bookname of the secondary reference. Just fixed in the sermons model - so may need to look at the sermon model too.

https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/bdfd9ae87dbeebd4d3c4ac278438b6d818bc16de

**Comment by st-anton** [comment]
Test ok
