### ISSUE TITLE
All studies lists: <p>...</p> does not allow child <div>

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#521]
`<p>..</p>` does not allow child elements like `<div>` ect. Thus the `<p>` 'around' the download and speaker icons lead to an html error. This also leads to a slightly higher row in the display.
With the help of http://validator.w3.org/ you can find the trailing `</p>`.
Example:
![list_p](https://cloud.githubusercontent.com/assets/2517417/6770587/ed35ca8c-d0c4-11e4-954b-a8410154f046.png)

**Comment by tomfuller2** [comment]
What happens if you select NONE as the html element around the media in the template?

**Comment by st-anton** [comment]
Do you mean: Omitting the `<p> </p>` in case of a media? Or would you kick out the `<div> </div>` and leave the icons as they are? I can try to do either.

Regarding the formatting, I have two more thoughts:
- leaving out the `<p> </p>` in case of an empty field. I hope, the list will be much more 'condensed' in case of very narrow displays (smartphones)
- What is the line `<div style="font-size: 0.6em;display:inline;position:relative;margin-bottom:15px;padding-right:2px;">`good for? it appears after the media icons. Is is needed to display some text or is it a leftover? Can it be removed?

**Comment by tomfuller2** [comment]
That's for the filesize. If you choose not to show filesize, doesn't that
go away?

It's lines 53-64 in site/helpers/media.php

Is there a better way to show the filesize?

**Comment by st-anton** [comment]
Yes, if the filesize should be hidden, the style disappears. Please also see #528

I try to improve the formatting.

**Comment by st-anton** [comment]
`What happens if you select NONE as the html element around the media in the template?` -> Yes, this does work. It is somehow misleading, that the default html element is `paragraph` for all items - also for media.
-> Closed
