### ISSUE TITLE
Frontend Latest Study: Displayed even if access level is not granted

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#522]
Setting the access level of the study to e.g. registered (or in my case: Memebers), the output gives warnings, if not logged in:
`Message You are not authorised to view this resource.`
`Error Access Forbidden`

Then (after the warnings of #518) the study is displayed, even if the user is not logged in.

I would expect to see the latest study, that I'm allowed to see, even if there is a newer one e.g. for members.

**Comment by bcordis** [comment]
@st-anton please retest and let me know if it was fixed.

**Comment by st-anton** [comment]
Still same behaviour. Clearing the cache and reloading the page does not help.

**Comment by st-anton** [comment]
A related effect occurs: If the latest study is unpublished or the access level is higher (i.e. access is not allowed), the message occurs: Study not found.

**Comment by bcordis** [comment]
So how should the error look?

**Comment by st-anton** [comment]
![linklatest](https://cloud.githubusercontent.com/assets/2517417/7712040/06295a72-fe6f-11e4-8fa9-04b7521aeee2.png)

**Comment by bcordis** [comment]
That sound like need to look at that more.

**Comment by bcordis** [comment]
I have teste this and it is working right now.
