### ISSUE TITLE
Backend new/edit Media: All servers are selectable, even if unpublished

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#524]
This will worrying the editor: What server should he select?
Another way would be to display an additional column with the actual published state, like it is in the selection of a study in the media form.

**Comment by bcordis** [comment]
@st-anton try testing this.

**Comment by st-anton** [comment]
The popup still shows all servers:
![server1](https://cloud.githubusercontent.com/assets/2517417/7622716/4dc64378-f9d2-11e4-99b6-fb52c3133d5a.png)

Then I found `search tools`and the possibility to select published servers only:
![server2](https://cloud.githubusercontent.com/assets/2517417/7622743/a4e189ec-f9d2-11e4-9687-52b94e648e03.png)
I think, this is what wee need!

**Comment by bcordis** [comment]
@st-anton Fixed. This was a error with the modal view so I have added the code to fix this view.

**Comment by st-anton** [comment]
Done.
