### ISSUE TITLE
Player/pdf show Notice

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#525]
You find it in your site (studies list display), clicking on a media. A popup windows open and the players show notices.
Example:
Notice: Undefined property: stdClass::$bookname in /home1/joomlaor/public_html/joomlaoregon_com/jbs/components/com_biblestudy/lib/listing.php on line 1929

**Comment by bcordis** [comment]
@st-anton this should be fixed.
