### ISSUE TITLE
Saving Media File lets download icon disappear

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#526]
A media file (e.g. mp3) that was migrated shows the speaker icon and the download icon. Opening the media file and saving without changing anything lets the download icon disappear.
New media files never show the download icon.
First I thought, it has to do with the parameter size, but it wasn't. Just a guess: Does it have to do with the server?

**Comment by bcordis** [comment]
This was a prametarter option in the old system need to make sure it is moved over right. looking.

**Comment by bcordis** [comment]
@st-anton @tomfuller2  Can you retest and see if I fixed this.

**Comment by st-anton** [comment]
Test ok -> closed
