### ISSUE TITLE
Selecting a file for restore does not work

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#527]
Admin - backup and restore - browse for a file. Click submit: "No file selected"

**Comment by bcordis** [comment]
@tomfuller2 is this still happening?

**Comment by bcordis** [comment]
@tomfuller2 I'm not able to reproduce this. can you please retest?

**Comment by bcordis** [comment]
@st-anton also could you test. Next version we are looking at removing this view. it is a duplicate almost of migrate.
@tomfuller2

**Comment by st-anton** [comment]
Works on my machine.
I agree: It would be fine to have one combined import function for old (migration) and actual (restore) db, if it is not too much effort.

**Comment by bcordis** [comment]
Fixed. Closing as will make new ticket when change.
