### ISSUE TITLE
Media filesize: Wrong parameter?

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#528]
Not sure, whether this a bug.
I tried to display the filesize, but it did not. Debugging it shows up, that the filesize always returns NULL.
$media->smedia is empty
$media->params->size would be the right information
So: How does \components\com_biblestudy\helpers\media.php lines 366 to 394 work?

**Comment by bcordis** [comment]
@st-anton This is do to there was no size specified when creating media link. I'm working on a idea to have the size updated on save of media.
