### ISSUE TITLE
Frontend biblestudy.css: a lot of leftovers ?

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#529]
In media/css/biblestudy.css I found a lot of tags, tat cannto be found in the code like: bsmsdetailstable, seriestable, seriesstudytable.
Are they leftovers and can be deleted?

**Comment by tomfuller2** [comment]
There should lots of those. If you can't find in the code they can be
deleted. Since changing the views over to taking their look from the site
template.

**Comment by bcordis** [comment]
Yes they are created by the lss file if you find them let me know and I'll clean them up. We need to create some new ones anyway.

**Comment by st-anton** [comment]
I collected information how the .css does work and got some ideas (and questions as well), how the situation may be improved:
- Currently the origin of the .css is the database table _bsms_style. Does it make sense to maintain the .css editor in the component? Each delevoper has a faster and more mighty editor (text highlighting, comparison...) than the buildt in editor.
- In the first attempt I was not aware, that the database is the master. So I first changed the .css file, then tried to adapt the database table. But saving overwrote the .css file and my work was lost. That was annoying.
- @bcordis you mention the lss (or .less?) file, the .css file is generated out of. Do you have a compiler this for? How is the result imported into the database table?
- I started to collect all the codes, that can be removed. And in fact, only a few will survive. @tomfuller2 you mentioned, that basically the look of the site template should be used. So the .css of the 9.0.0 version will be quite short.
- During migration the database table is used, somehow modified (\admin\helpers\dbhelper.php lines 342 to 350 seems to do so) and written to file. But as the old stuff is nearly completely removed, this is no more helpful to use the old items.
- As far as I remember, you planned to release a 8.0.9 version to fix the format of this table. Is this really needed / worth the work?
**Conclusion**: Does it make sense to simply drop the table _bsms_style, remove the css editor and deliver the css file as it is?

**Comment by st-anton** [comment]
Created pull request #531 with reviewed database table _bsms_style as well as biblestudy.css

**Comment by st-anton** [comment]
@bcordis: If you want to review the .less file, here are the changes:
Note 1: Several of them appears in biblestudy.less as well
- bsm_teachertable_list deleted, note 1
- bsm_teacherthumbnail_list deleted
- bsm_teachertable used in \com_biblestudy\site\views\teachers\tmpl\default_custom.php
- landingtable, landingrow, landingcell, landinglink used in \com_biblestudy\site\helpers\landing.php
- termstext, termslink used in \com_biblestudy\site\views\terms\view.html.php
- podcastsubscribe, podcastheader used in \com_biblestudy\site\helpers\podcastsubscribe.php
- podcastlinks deleted, note 1
- fltlft used in \com_biblestudy\admin\models\fields\modal\seriesdetail.php
- subscribelinks deleted
- listingfooter, listintro used in \com_biblestudy\site\views\seriesdisplays\tmpl\default_custom.php
- main deleted, note 1
- bsdropdownmenu used in \com_biblestudy\site\views\seriesdisplays\tmpl\default_main.php
- bslisttable used in \com_biblestudy\site\views\teacher\tmpl\default_custom.php
- component-content deleted, note 1
- pagenav deleted, note 1
- bsmsdetailstable deleted, note 1
- bsdetailstable deleted
- titletable deleted, note 1
- recaptcha_widget_div deleted, note 1
- bsmsmoduletable used in \mod_biblestudy\tmpl\default_custom.php
- seriestable deleted, note 1
- seriesstudytable deleted, note 1
- tool-tip, tool-title, tool-text, custom-tip, custom-title, custom-text deleted, note 1
- bsm_teacherthumbnail deleted
- bsmbutton deleted, note 1
- toolbar deleted, note 1
- bsmsshare deleted, note 1
- landinglist used in C\com_biblestudy\site\views\landingpage\tmpl\default.php
- landing_label, landing_item, landing_title, landing_table, landing_td, landing_separator used in \com_biblestudy\site\views\landingpage\tmpl\default.php
- biblestudy_landing used in \com_biblestudy\site\views\landingpage\tmpl\default.php
- showhide used in \com_biblestudy\site\views\landingpage\tmpl\default.php
- popuptitle, popupwindow, popupfooter used in \com_biblestudy\site\views\popup\tmpl\default.php

**Comment by bcordis** [comment]
Less file creates the css file. So we need to update the less or when compiling the component it will do the css file.

**Comment by st-anton** [comment]
During migration (I used a 8.0.0 database), the \n in the _styles are treaded wrong:
![css](https://cloud.githubusercontent.com/assets/2517417/7783471/150696a4-0144-11e5-83fc-2ae03af32a6b.png)
With this, the generated biblestudy.css is inoperative.

Beside this bug, I assume, that it makes no sense to migrate the _styles table as the responsive code in fact does not use the old fashioned css entries.
In my eyes, this is another reason (beside https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/529#issuecomment-87831034), why the _styles table should be dropped. css and less should be the master.

**Comment by bcordis** [comment]
This was do to a bug in 8.0.9- on the export of there do. I have fixed that
problem. It was a double escaping the export.

Try updating the export file and then migrate the exported dB.

I think we should also move away from the dB to as it makes problems.

On Saturday, May 23, 2015, st-anton <notifications@github.com> wrote:

> During migration (I used a 8.0.0 database), the \n in the _styles are
> treaded wrong:
> [image: css]
> <https://cloud.githubusercontent.com/assets/2517417/7783471/150696a4-0144-11e5-83fc-2ae03af32a6b.png>
> With this, the generated biblestudy.css is inoperative.
>
> Beside this bug, I assume, that it makes no sense to migrate the _styles
> table as the responsive code in fact does not use the old fashioned css
> entries.
> In my eyes, this is another reason (beside #529 (comment)
> <https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/529#issuecomment-87831034>),
> why the _styles table should be dropped. css and less should be the master.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/529#issuecomment-104878954>
> .
>


-- 
Sent from Gmail Mobile

**Comment by st-anton** [comment]
I used a db of 8.0.0. I guess the problem was in all the time. Should be force the user to update to 8.0.9 first, then export and import? With this the migration from 7.x.x and 8.0.0 within the 9.0.0 would not make sense.
Anyway, lets drop the _styles table and move to plain css file and don't think about this anymore.

**Comment by bcordis** [comment]
I have created a db fix for this closing until we see it again.
