### ISSUE TITLE
Export database: New line characters in _bsms_styles are dropped

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#530]
After importing it again, there is only one veeery long line. This is nearly impossible to read and modify.
Example:
install_defaults:
`/* New Teacher Codes */\r\n#bsm_teachertable_list .bsm_teachername\r\n{\r\n    font-weight: bold;\r\n    font-size: 14px;\r\n`

after export:
`/* New Teacher Codes */#bsm_teachertable_list .bsm_teachername{font-weight: bold;font-size:`

**Comment by st-anton** [comment]
Should it be fixed or should the _bsms_styles table be dropped? See #529

**Comment by tomfuller2** [comment]
This is a problem with the migration - it affects both this and the
template files. I tried to figure this out - but wasn't able to get the
if/then to work - basically not doing the removal of \r\n characters in
certain tables.

**Comment by bcordis** [comment]
This was a big problem and I thinks i fixed this on import but not on export. still need to look into this.

**Comment by tomfuller2** [comment]
bsms_styles
bsms_templatefiles
bsms_studies_studytext & studyintro

All need to have new lines intact I think. I tried to fix this but failed.

**Comment by bcordis** [comment]
@tomfuller2 So there is a error with new lines on those tables?

**Comment by bcordis** [comment]
@tomfuller2 @st-anton Ok I think i found a solution to the export and import function. Removed escaping from the Quote function. This will keep it cleaner and then hav replaced all \r\n and \r with \n

This will make a cleaner code.

**Comment by st-anton** [comment]
In the exported sql file, the __styles table is plain ascii with carriage return, not with `\n`. I think, this is not the favoured format...
Find it in my database I sent you.

**Comment by st-anton** [comment]
Tested ok
