### ISSUE TITLE
Frontend Studies List Display: Crashes with parser error

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#534]
Template setting: 'System format':
DateTime::__construct(): Failed to parse time string (Sonntag, 01. Februar 2015) at position 0 (S): The timezone could not be found in the database

Template setting '2010/09/01':
DateTime::__construct(): Failed to parse time string (2015/Feb/So) at position 4 (/): Unexpected character

Please find in: http://feg-muenchen-nord.de/fegtest/index.php/study-list-all
This is my first test with Joomla 3.4.1; I cann't remember this bug before (J 3.6.6)

**Comment by st-anton** [comment]
The bug disappear, when a custom code for date is set like j.n.Y

**Comment by bcordis** [comment]
@st-anton Can you reproduce this or is it gone?

**Comment by st-anton** [comment]
Not gone :-(

**Comment by bcordis** [comment]
@st-anton Can you point me to how you produce the error so i debug it better?

**Comment by st-anton** [comment]
I will send the database. Simply remove the php date code from the Templates -> Default -> Study List View -> Set Custom PHP String To Time

**Comment by st-anton** [comment]
Just sent a new db and the code by mail

**Comment by st-anton** [comment]
One step ahead: It happens when Joomla language debugger is enabled.
This sounds plausible: The date string is parsed once more for correct translation. Sounds like a Joomla core problem. I will try to get a little deeper or give up soon.

**Comment by st-anton** [comment]
Internet is full of discussions about this issue. It seems to be related to:
- tmp or log folder not writable
- tmp or log folder not set correctly during Joomla installation
- bug in Joomla 3.0.x
- mySQL driver PHP is using
- php.ini settings
- setting in plugins/system/yt/includes/libs/yt-minify.php

and others.
We should have in mind, if somebody got a problem like this.
This issue can be closed.
