### ISSUE TITLE
Adding new study introduces an "A"

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#535]
Enter a new study - every one adds an "A" as a topic. This creates a large list of capital A's in the topic list. This is in version 8.08. Not sure if it happens in version 9.

**Comment by bcordis** [comment]
Thought I had fixed this in the 8.x branch and in development.

**Comment by bcordis** [comment]
@tomfuller2 This has been fixed in latest version please test.
