### ISSUE TITLE
Folder of images is Joomla default, but not com_biblestudy

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#536]
Add / edit Teacher:
I expected the folder \media\com_biblestudy\images to be used for teacher images. Also Billy Sunday is there. Instead of this, folder \images is used. 
Imho the Joomla folder should not be used.

**Comment by st-anton** [comment]
All fields refer to the \images folder. This comes from the use of field type 'media'.
https://docs.joomla.org/Media_form_field_type says, that `directory (mandatory) is the directory from which the user will be able to choose a file. This attribute should be relative to the top level /images/ folder.`
So we never will be able to access \media\com_biblestudy\images

**Comment by st-anton** [comment]
Seems to be not that easy:
/media/ seems to be intended to be filled during installation, but not touched afterwards.
/images/ is the only folder, that the media manager can access. But files cannot be placed here by installation manifest; it needs to be done manually. For example PhocaGallery component does it by /install/script.php.
In my opinion, all the images that are set in the backends setting, should be copied to the /images/com_biblestudy folder. Currently I find: BillySunday, download, speaker. Are there others?

**Comment by bcordis** [comment]
You can hard code the media manager to use the folder but that would need some work. I know it is possible.

**Comment by st-anton** [comment]
Does it mean some kind of hack in the Joomla core? I don't like that.
Digging deeper in the docs, it gets clearer to me, that /media/ should be used for all images, js and css the extension brings with the installation. Unlike this /images/ is used for user uploading images for the content. 
Example for the discussions in the past: google groups discussion within https://docs.joomla.org/Manifest_files#Media_files

I think, the change is nat that critical: BS 8 already uses the media manager, user already uploaded images to the /images/ folder. So migration should not be of concern.
To make it more clear for new users and to avoid bugs like 'I'm looking for speaker.png, but cannot find ist in the media manager', I suggest to:
- set up a folder /images/biblestudy
- copy the images to this folder
during installation / update. If it's ok for you, I would do it. (During this work, I would clean up the images #539 as well).

**Comment by bcordis** [comment]
There should be a way to point to a folder in the xml code for that view.

**Comment by bcordis** [comment]
Ok lets do that. I'll start making the code for migration.

**Comment by st-anton** [comment]
Works well.
