### ISSUE TITLE
Backend Servers Batch gives notice

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#538]
The popup windows comes up with
 Notice: Use of undefined constant BIBLESTUDY_CHECKREL - assumed 'BIBLESTUDY_CHECKREL' in ...\administrator\components\com_biblestudy\views\servers\tmpl\default_batch.php on line 16
Call Stack
Time	Memory	Function	Location
...shortened...
11	1.1785	5236248	BiblestudyViewServers->display( )	..\legacy.php:690
12	1.2091	5980400	JViewLegacy->display( )	..\view.html.php:109
13	1.2091	5980424	JViewLegacy->loadTemplate( )	..\legacy.php:209
14	1.2105	6039072	include( '...\administrator\components\com_biblestudy\views\servers\tmpl\default.php' )	..\legacy.php:670
15	1.2288	6303672	JViewLegacy->loadTemplate( )	..\default.php:188
16	1.2299	6326000	include( '...\administrator\components\com_biblestudy\views\servers\tmpl\default_batch.php' )	..\legacy.php:670

**Comment by bcordis** [comment]
Fixed @st-anton test.

**Comment by st-anton** [comment]
Fixed ok -> closed.
Batch itself crashes -> new issue will be opened
