### ISSUE TITLE
Corrupt images / icons, leftovers and menu icons

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#539]
- I found 28 images and icons, that cannot be displayed because of malformed header information. There are both .png and .gif icons. Some of them, I can find in the source code, some of them seems to be leftovers.
- Leftovers: A lot of icons I cannot find in the source code. Example: \media\images\icons contains 21 files names icon-32-*.png, but only 4 of them are used.
- Menue items: As far as I see, Joomla 3.4.x does not use menu icons anymore, so this can be removed as well:

![menu25](https://cloud.githubusercontent.com/assets/2517417/7102835/975dd124-e08f-11e4-9aa8-e1b6672f5bc1.png) ![menu34](https://cloud.githubusercontent.com/assets/2517417/7102836/9a94e0d0-e08f-11e4-83b3-dd234d3113ba.png)

**Comment by st-anton** [comment]
The menue items are not displayed in the isis template - it does not have to do with Joomla. So menue icons should be kept.

**Comment by st-anton** [comment]
I tried to find the icons of the title and got confusing information.
https://docs.joomla.org/JToolBarHelper/title says:
`JToolBarHelper::title('title','sample');` *This will make the page title "title" and add a class to the toolbar title based upon the second parameter. The css class will be prefixed with "icon-48-". In the example above the class would be: icon-48-sample.*
So: the second parameter is not an image. **This need to be fixed in our sources.**

Now the confusing part begins: The function `JToolBarHelper::title` is dependent of the template!?!?
I tested `JToolBarHelper::title(JText::_('JBS_CMN_STUDIES'), 'studies');` and got
template isis: `<span class="icon-studies"></span>`
template hathor: `<div class="pagetitle icon-48-studies">`
How can we handle this?

**Comment by st-anton** [comment]
Corrupt icons: Up to 7.1.2 the icons are ok. In 8.0.0 some of the icons are renewed and (nearly) all of them are corrupt and cannot be displayed.
The renewed files are roughly 1.5 to 2 times bigger than the old ones. Maybe this is a bug in the image processing program.

**Comment by bcordis** [comment]
Fixed.
