### ISSUE TITLE
Import Database crashes

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#543]
Export the database and then import a database from end of March 2015:
This makes the database invalid.
Error message
1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{\'path\':\'\'}'',`media`=''' at line 1 SQL=INSERT INTO `fmnj34_bsms_servers` SET `id`='7',`server_name`='Default',`published`='0',`asset_id`='396',`access`='1',`type`='legacy',`params`=''{\'path\':\'\'}'',`media`='';

**Comment by st-anton** [comment]
Not sure, whether the database was a export file or a complete Joomla database from phpMyAdmin. I have to set up my site again.

**Comment by bcordis** [comment]
Let me know if I need to fix something? I'm still able to do my import.

**Comment by st-anton** [comment]
After restoring the site completely from an (windows) backup, I reproduced the bug:
Export the database
modify something - in my case: save a css as copy
Import the database
This gives error: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{\'path\':\'\'}'',`media`=''' at line 1 SQL=INSERT INTO `fmnj34_bsms_servers` SET `id`='7',`server_name`='Default',`published`='0',`asset_id`='396',`access`='1',`type`='legacy',`params`=''{\'path\':\'\'}'',`media`=''; 
I will send the exported database to you, there you can reproduce #534 (see there)

**Comment by bcordis** [comment]
@st-anton try retesting I think i fixed this now. I'll try and do some more testing to.

**Comment by st-anton** [comment]
Tested ok -> closed

**Comment by st-anton** [comment]
Crashes with token error: `The most recent request was denied because it contained an invalid security token. Please refresh the page and try again.`

**Comment by st-anton** [comment]
Works well -> closed

**Comment by st-anton** [comment]
Happens again on the current version

**Comment by st-anton** [comment]
Sorry, wrong issue
