### ISSUE TITLE
Frontend Study Admin: Filter of menue setting does not work

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#544]
When setting up a new menue entry for admin of a study, a filter can be set:
![menu1](https://cloud.githubusercontent.com/assets/2517417/7573127/9b6d926c-f823-11e4-9b27-b077da1f3c01.png)

But this selection has no effect. Simply all teachers ... are displayed

Imho, this filter does not make much sense. Can it simply be dropped?

**Comment by tomfuller2** [comment]
The filtering works properly. I am not seeing this bug.
