### ISSUE TITLE
Frontend new / edit media: Yellow message field -> Expect green

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#545]
Whne saving a message, the next page says `Message Item successfully submitted.` within a yellow box. It is not absolutely clear, whether this is a warning.
It would be nice to see a green colored field.

**Comment by st-anton** [comment]
Same situation on save of a study

**Comment by bcordis** [comment]
@st-anton test @tomfuller2

**Comment by st-anton** [comment]
No change, still yellow

**Comment by bcordis** [comment]
@st-anton This is a core message and we would have to hack their system. I'm not looking at doing this as it would make us maintain too much code.

**Comment by st-anton** [comment]
OK, don't let us hack the core.
