### ISSUE TITLE
Backend new study: Save and add media does act as expected

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#546]
Different than #459, the `save and add media`button saves the study, but the next page is again the study edit page. I expected the page to add new media.
Also see #547 .

**Comment by bcordis** [comment]
@st-anton This will need to be put off as this is not a bug. This was that way in the old system and will need to be change in this version.

**Comment by st-anton** [comment]
OK - It's ok for me. Closed
