### ISSUE TITLE
Backend new study and add media: Returns to study edit

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#547]
When I edit a study, the tab `Media files for this Study` shows the button `Add media file`. (For new studies the button is `save and add media`; see #546). I press the button and enter the media file (still the server mechanism is broken) and `save and close` the media file.
Now I expect to return to the studies list. Instead, I return to the edit of the present study. This does not make sense.

**Comment by tomfuller2** [comment]
It is supposed to return to the study, not the studieslist. That way you
can add multiple media files to a particular study without having to go
back into the study record.

**Comment by st-anton** [comment]
Okay, this makes sense.
