### ISSUE TITLE
Frontend Admin study list: New studies are not editable for Editors

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#548]
During all my tests I added studies on frontend as well as backend. On frontend I was logged in as SuperUser as well as Editor. On backend I was logged in as SuperUser only.

Curious behaviour when logged in as Editor: All old studies from the migration can be edited, as there is a link present on the study name. All new studies - and even modified studies - cannot be edited, there is no link.
Fixing the assets does not change the situation.
This bug is critical, because a Editor cannot change his own studies.

The asset of a migrated study has no rule. This is simply empty.

The rule on the asset of a new study says: {"core.delete": "1":0,"9":0,"6":1,"7":0,"2":0,"3":0,"4":0,"5":0,"8":0},"core.edit":{"1":0,"9":0,"6":1,"7":0,"2":0,"3":0,"4":1,"5":0,"8":0},"core.create":{"1":0,"9":0,"6":1,"7":0,"2":0,"3":1,"4":0,"5":0,"8":0},"core.edit.state":{"1":0,"9":0,"6":1,"7":0,"2":0,"3":0,"4":0,"5":1,"8":0},"core.edit.own":{"1":0,"9":0,"6":1,"7":0,"2":0,"3":1,"4":0,"5":0,"8":0}}

**Comment by bcordis** [comment]
@st-anton on the admin page have you verified that the editor has permission to edit the record. I know on migration the permission may not work on the new site. let me know how this test out?

**Comment by st-anton** [comment]
Now the editor can edit studies that were added by admin or editor recently. But he cannot edit migrated one; that's not a big problem.
Need to play with this and see whether we can close this issue.

**Comment by bcordis** [comment]
@st-anton try running fix assets and see if that fixes it. i added some more code to help with migrating. Also placed safety checks to make sure code cannot be run without it coming from joomla.

@tomfuller2 FYI this is a big update to fix a lot of safety checks. Realy close now.

**Comment by tomfuller2** [comment]
Thanks so much Brent and Anton!

**Comment by st-anton** [comment]
Works
