### ISSUE TITLE
Frontend edit mediafile: Save generates duplicates db entry

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#550]
After saving a present mediafile, there are two enties in the database.

**Comment by bcordis** [comment]
Can you verify this as of right now it is not duplication. I can't see this on backend or the front end. this could be do to a migration you are seeing.

**Comment by st-anton** [comment]
Verified with up to date php code.
Steps in frontend:
- add a new media; on the page only the tabs `General items`and Àccess Control`are present
- enter study, create date and a legacy server; as no further tabs appear needed for the legacy server, you need to save the item.
- select the new item (it need to be the item with the highest ID), and press edit
- now all tabs for legacy server are present; fill them in
- save
- have a look in phpMyAdmin (I tested with two studies):
![media](https://cloud.githubusercontent.com/assets/2517417/7662528/aedc2e7a-fb5d-11e4-9a04-206a2a3c832d.png)

The first entry is checked out (what does this mean?)
I got the impression: As long as the reloading of the server does not work, we will get problems again and again.

**Comment by st-anton** [comment]
Still the same behaviour.
I set up a new site without migration data (only the 'Billy Sunday' default database coming with the installation). Also I double checked, whether I have the latest sources.

**Comment by bcordis** [comment]
@st-anton Look like we need to do a hangout and see what is happening. Right now i'm not seeing the it reproduce after deleting the duplicate. Email me times.

**Comment by st-anton** [comment]
Just an idea: I have php  5.4.7 on my machine - this is quite old, but should run.
(Joomla is 3.4.1 german, so this is up to date.)

**Comment by bcordis** [comment]
@st-anton I have fixed the save problem took some time. please Test. @tomfuller2

**Comment by st-anton** [comment]
Cannot test; see #562

**Comment by bcordis** [comment]
@st-anton fixed #562 please Retest

**Comment by st-anton** [comment]
Test ok! Closed
