### ISSUE TITLE
 Backend new/edit server: selecting server clears field of server name

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#552]
When adding a new server or edit a present one: Changing the server reloads the page (needed for addons) and clears the server name.
Similar than #498

**Comment by bcordis** [comment]
@st-anton Not seeing clearing. please update files and retest.

**Comment by st-anton** [comment]
Retested with up to date php code, not solved.
Steps:
- new server
- on the next page two tabs are present: `Details` and `Template access rules`
- enter a name like 'MyServer'
- select a legacy server type
- as soon as the popup window closes, the page begins to reload (the trigger works here!)
- the tabs for legacy type server appear, but the name of the server is gone
As far as I see, the server selection in the server view and media views (frontend and backend) does either not reload the tabs for the server type (trigger does not work) or it does reload and all entered fields are cleared (trigger does work).

**Comment by bcordis** [comment]
@st-anton Right now i'm trying to remove all reload till we get the the selection fixed. Can you confirm that the page doesn't reload right now?

**Comment by st-anton** [comment]
It does reload und thus clear the server name field.

**Comment by bcordis** [comment]
@st-anton Ok I need to see this on your server. I'm not seeing any JS code on the Development branch that will do this. Can you help me out by checking your code on your dev box to the development branch and see if you see a difference. I'm not sure where the call is coming from on your system.

**Comment by bcordis** [comment]
@st-anton Ok now i found it. needed to read better. I'm looking into a solution now.

**Comment by bcordis** [comment]
@st-anton test @tomfuller2

**Comment by st-anton** [comment]
Test ok! :-)) Closed
