### ISSUE TITLE
Shorten html code of study listings

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#555]
Currently the html code is veeery long, when a study list is presented in the frontend. 30000 to 50000 characters in one line is hard to read. Please modify site\components\com_biblestudy\lib\listing.php  line 434 from
`$list .= $value;`
to
`$list .= "\n\t" . $value;`
With this, each study gets its own line with 1500 to 2000 characters. This has no influence on the rendered output to the user.
Thanks!

**Comment by bcordis** [comment]
@st-anton Sorry that will not work.  It just prints the info onto the page not braking the print out code.

**Comment by st-anton** [comment]
You are right, when writing with single quote:
![listing_singlequote](https://cloud.githubusercontent.com/assets/2517417/7671893/1dae49c6-fce1-11e4-9934-bc19a8a18054.png)

But writing with double quote, this works:
![listing_doublequote](https://cloud.githubusercontent.com/assets/2517417/7671895/2c675a34-fce1-11e4-956f-2bf6e7a835bd.png)

**Comment by st-anton** [comment]
Thanks!
