### ISSUE TITLE
Menue entry Landing: Shift the Ascending/Descending to template

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#558]
Template defines, which entries are visible on the landing page. Also there is a selection of 'Default date Ascending/Descending). But the Ascending/Descending sort is set on the menue entry.

I think, the sort settings should be moved from the menue settings to the template. I cannot imagine that somebody sets up two different landing pages with different settings. The template should contain all the settings encapsulated.

**Comment by tomfuller2** [comment]
I agree we should probably just have it one place or the other

**Comment by bcordis** [comment]
@st-anton @tomfuller2 Test.

**Comment by tomfuller2** [comment]
Tested and works.
