### ISSUE TITLE
php 7

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#559]
Expected October 2015
https://wiki.php.net/rfc/php7timeline
Some incompatible changes are expected

**Comment by bcordis** [comment]
Interesting info maybe next year.

**Comment by bcordis** [comment]
JBSM 9.0.0 ready for php7

**Comment by bcordis** [comment]
now we have moved to 9.0.1 all ready for php7 closing.
