### ISSUE TITLE
Backend new legacy server: Image is mandatory? URL is not?

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#560]
Adding a new legacy server needs some additional entries. Questions:
- The URL is not mandatory. Is this ok? Does an empty field mean: Use the URL of the site?
- the image field is mandatory. Why?

**Comment by bcordis** [comment]
Image is used as a default for media image but is not required. Removed.
URL is the root server name of the hosting environment. if local then you must put that info in.
