### ISSUE TITLE
Backend new legacy server: Save and close checks mandatory fields, save does not

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#561]
Adding a new legacy server and save: Mandatory fields like image (see #560) are not checked; save displays a message `Item successfully saved.`. I think, this is not ok.
If I use 'save and close', the mandatory fields are checked and save is rejected. This is the normal behaviour.

**Comment by bcordis** [comment]
Not sure there is anything I can do here. I could make the image not mandatory. The image is a default used for that type of media so on a page it shows the icon. I do need to finish the new copy to image folder so they can select them.

**Comment by bcordis** [comment]
I'm going to remove the Requirement. Not needed to be Required. We can revisit this if needed.

**Comment by st-anton** [comment]
The functionality is needed - sooner or later. Currently, we need it for #563

**Comment by bcordis** [comment]
Fixed.

**Comment by st-anton** [comment]
Fixed
