### ISSUE TITLE
Frontend new media: Server selection ends in 'invalid form'

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#562]
Selecting a server (tested Anazon and legacy) let a popup message appear: 'invalid form'
![server1](https://cloud.githubusercontent.com/assets/2517417/7733967/0c823dde-ff33-11e4-80cd-d5a3357ad99f.png)
Klicking on OK lets the server selection form (modal box) disappear. But neuther `save and close` nor `cancel` (!!!) allows leaving this page, always the popup `invalid form` comes up.

**Comment by bcordis** [comment]
Amazon is not ready for production and will need to be removed before beta.

Thanks,
Brent Cordis
2406 Hermitage Park Dr.
Hermitage, TN 37076
615.429.6426

**Comment by st-anton** [comment]
Happens with all types of servers. Happens also with published and unpublished servers.

**Comment by bcordis** [comment]
That is not good I'll look at it ASAP.

**Comment by bcordis** [comment]
Fixed the save problem.

**Comment by bcordis** [comment]
@st-anton Can you retest.

**Comment by st-anton** [comment]
Works well for legacy, amazon and local - except for ftp server.
Loading the addon for ftp server ends in error `Fehler JForm::getInstance could not load file`.

**Comment by bcordis** [comment]
@st-anton @tomfuller2 Removing Amazon and FTP and ExtenrlLink for now. 9.1.0

**Comment by st-anton** [comment]
Both frontend and backend ok.
