### ISSUE TITLE
Server Local: Is Base URL mandatory?

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#563]
Base URL is written with `*`. Does this mean, it is mandatory?
If yes, it should be checked before saving (also see #561).
If not, the asterisks should be removed. 
And: Is it needed at all?

Another inconveniance: The phrases in admin\com_biblestudy\addons\servers\local\local.xml are not translated; neither the description nor the field description (*Base URL*)

**Comment by bcordis** [comment]
Any thing with a * by it is Mandatory. Needs to be looked into.

**Comment by st-anton** [comment]
I add  `required="true"` to
\administrator\components\com_biblestudy\addons\servers\local\local.xml  line 10
Now I got the effect of #561. I think, the  `required="true"` is needed; also I will reopen #561

**Comment by bcordis** [comment]
@st-anton This is mandatory and should be required.

**Comment by bcordis** [comment]
Working now. closing.
