### ISSUE TITLE
Frontend / Backend new / edit media: Local Server has strange field 'status'

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#564]
When adding / editing a media in frontend or backend with server 'local' I get a tab `publishing`.
Within this tab there is a field `status`, but there is no value or selction to be set; no dropdown or similar.

**Comment by st-anton** [comment]
Now it is even more curious: The only selectable setting is 'unpublished', but published - unpublished - trashed is settable in the `General items`tab.
What is this selection good for?

**Comment by bcordis** [comment]
@st-anton Fixed.

**Comment by st-anton** [comment]
Test ok
