### ISSUE TITLE
Issues with backend media add

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#565]
Added a new legacy server with a path: www.calvarychapelnewberg.net/MediaFiles/2015/
Added a new media file. Chose server. No options for parameters. Had to Save, then all parameters came up. Is this expected behavior? If so we need to EXPLAIN this to the user.

When I saved I had options such as filename. Tried upload. Seemed to be successful but file was not actually uploaded to that server.

Filesize link is not working now.

though I chose a server, I was still offered to choose image and mimetype. This is supposed to come from the server entry now, yes? We are still making people upload their own images instead of offering them choices like before - is that true?

**Comment by bcordis** [comment]
Please update to new code as this is has been fixed in the development branch and will automatically reload the page with the newest stuff and you will not lose your savings of the core fields.

**Comment by tomfuller2** [comment]
I was using development branch. Pulled just this morning

**Comment by bcordis** [comment]
The selecting a server on the media edit page should reload the page on selection of the server? Did that happen?

**Comment by bcordis** [comment]
@st-Anton can you test this and see if it is happening to you? I'm not seeing it on my chrome browser.

**Comment by st-anton** [comment]
When selecting the server, the additional parameters are loaded and displayed. This works well. (Firefox browser)

Upload: I'm on a local host on my PC (xampp), so I expect the upload will not work. Cannot test with my environment.

Filesize does not work, always 0

Image is a mandatory field. If the user should enter an icon here, we should offer the default icons (see #536)

**Comment by bcordis** [comment]
Upload should work on local host if not we have problem. Let me know. I need to remove this upload system from all other systems then local till we get support for it. Local I need to add some additional fields as they are missing.
