### ISSUE TITLE
Component & Module fatal error

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#566]
Fatal error: Class 'JBSMMedia' not found in /home1/joomlaor/public_html/joomlaoregon_com/jbs/components/com_biblestudy/lib/listing.php on line 2134

With module enabled this is the error - I can't get any more details on this from my server. Site dies.
When going to study listing get same error and site dies.
Using code as of 5-23-2015

**Comment by bcordis** [comment]
Is the is on development branch or is this on the eight point X branch?

**Comment by tomfuller2** [comment]
Development

**Comment by tomfuller2** [comment]
There must have been old files that persisted. I replaced all the files on the joomlaoregon/jbs site and now I get a different error:
Table 'joomlaor_jo5759.s6hej_bsms_folders' doesn't exist SQL=SELECT media.*,server.id as serverid, server.server_path as spath,folder.folderpath as fpath,image.media_image_path AS impath, image.media_image_name as imname, image.path2,study.media_hours, study.media_minutes, study.media_seconds,mime.mimetext FROM s6hej_bsms_mediafiles as media LEFT JOIN s6hej_bsms_servers AS server ON server.id = media.server LEFT JOIN s6hej_bsms_folders as folder ON folder.id = media.path LEFT JOIN s6hej_bsms_media as image ON image.id = media.media_image LEFT JOIN s6hej_bsms_studies AS study ON study.id = media.study_id LEFT JOIN s6hej_bsms_mimetype as mime ON mime.id = media.mime_type WHERE media.id IN (2902,2903,2904,3436,3437) AND media.published = 1 ORDER BY media.ordering, image.media_image_name ASC 
Not sure what file this query is being run from.

**Comment by bcordis** [comment]
Still looks like a file is messed up will have to search for that file. I'll look at this tonight when I get back.

**Comment by bcordis** [comment]
@tomfuller2 I have looked through all our code and we do not use #__bsms_folders in any of it. Please recheck and see what is up.
