### ISSUE TITLE
Administration check assets throws token error

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#570]
Checking the assets get: The most recent request was denied because it contained an invalid security token. Please refresh the page and try again.
Going back to admin page, logout of backend or refresh of the page does not change the situation.

**Comment by st-anton** [comment]
Check does work now. I see an additional (?) column `JBS_ADM_ARULESROWS` that is not translated. Also there is no explanation of this column in the footer of the table. (I get a mass of red numbers here.)

**Comment by bcordis** [comment]
if you have red numbers need to do Fix. sorry for that. I have updated this. now.

**Comment by st-anton** [comment]
Fixed, ok.
