### ISSUE TITLE
Frontend / Backend upload to local server: Unclear how it should work

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#574]
I added a local server, the path is `http://localhost/j34_test/media/com_biblestudy/studies`
Is this a correct path?

When adding a new media, I select this server, then I have to fill in the tab 'Upload'. What does the field 'Enter an upload path' expect? The URL (see above)? The path, where the file is taken from?

The I klick on 'Add file' and select a media file from my harddisc. Pressing 'upload' shows a green progress bar. But I cannot find the uploaded file somewhere within my server filesystem (in my case: htdocs). Where is the file uploaded?

In the sql, the bsms_mediafiles -> params say: {"upload":"http:\/\/localhost\/j34_test\/media\/com_biblestudy\/studies"}. There is no filename stored.

**Comment by tomfuller2** [comment]
I experience the same thing. File does not appear to actually upload

**Comment by st-anton** [comment]
...and we need to explain it better.

**Comment by bcordis** [comment]
I'll have to fix this. file should upload to the correct folder. I'll retest for this.

**Comment by bcordis** [comment]
@st-anton @tomfuller2 Should be fixed now.

**Comment by st-anton** [comment]
I installed the component on a real server and tried to upload a media.
First attempt was to press the `Add File` button (is it a button?). Nothing happened.
![upload](https://cloud.githubusercontent.com/assets/2517417/8621773/bab46b40-2727-11e5-92ad-e607ec364f8e.png)
The `upload` button has no reaction as well.
Then I add a filename like `c:\temp\study.mp3` and pressed the buttons again. No reaction at all.

**Comment by st-anton** [comment]
Same for Frontend. No reaction.

**Comment by bcordis** [comment]
@st-anton @tomfuller2  please retest as this should be fixed now.
