### ISSUE TITLE
Default images

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Joomla-Bible-Study#576]
There is a problem with the way we do the default images. If I code them into the View it could make it every time a user saves the data the default would apply even if they did not want it.

The only thing i would like to find a way to apply defaults on New creations not edits of existing records.

@tomfuller2 @st-anton  Please let me know how you feel about this.

!!This almost goes for all default values!!

**Comment by tomfuller2** [comment]
Why couldn't there be a default images drop down, like we have now, and a
way to upload a new image. If the upload a new image field is filled in,
then it doesn't use the value from the default images field. Does that
answer your question?

**Comment by st-anton** [comment]
I understand the question in a different way: Like a new study gets default values (teacher, location...) the image should be assigned to the new study. I think, this is simply the same way default values works today. If there is no default image, then the user has to assign an individual image every time.
We should create no different way or further automatic.
@tomfuller2 : The media manager already allows upload, so there is no extra need.

**Comment by bcordis** [comment]
Is there any time when they do not want to use a image?

**Comment by bcordis** [comment]
A little more.

A person makes a new study but does not want to us a image ( other default valued field) so they clear the field and save. When they come back to that study to edit it they get the default value again and them if they forget to check it and save the new default value saves.

**Comment by tomfuller2** [comment]
A user should not set a default image if they don't want to have to deal
with it. I think I agree with Anton's approach here.

**Comment by bcordis** [comment]
Ok i'm adding the code back in.

**Comment by st-anton** [comment]
The behaviour is unexpected to me: If I edit a present teacher without an image, but having defined a default image, it is filled in in the field. This looks like the the teacher has this image in the database, even if it is not.
My suggestion: Filling in the default image the same way as other default entries are filled in (example for study edit):
`empty($this->item->studytitle) ? $this->admin_params->get('booknumber') : $this->item->booknumber`
With this the default value is only filled in, if the mandatory field (i.e. teachername) is empty. So the default value is filled in an empty form, but not when edit an present form.

**Comment by bcordis** [comment]
@st-anton Can you point me to ones that are not doing this. I have a lot of other bugs to look over.

**Comment by bcordis** [comment]
I have also update the code to now only add defaults to the page on new creation not editing a old one.
