### ISSUE TITLE
Auto import of duration to media files?

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#58]
Comment from David Roy Slentz:

Would it be possible to import the duration of the file just like I do with the size of the file? Also add back in the filesize like in JBS 6 - with lookup of filesize

**Comment by bcordis** [comment]
File size is done still need to get duration fixed on save.

**Comment by bcordis** [comment]
Not possible with protocol right now to do duration.  FileSize will lookup automatically on save of media if size field is blank or 0.
