### ISSUE TITLE
Folder \images\BibleStudy with upper case letters?

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#580]
All the Joomla folders have lower case letters only. So I would prefer `biblestudy` instead of `BibleStudy`.

**Comment by bcordis** [comment]
@st-anton should be fixed now.

**Comment by st-anton** [comment]
Now there is no folder generated during installation anymore

**Comment by st-anton** [comment]
Ups, suddenly during the test session it is there !??!

**Comment by bcordis** [comment]
It only creates the folder on save.

On Tuesday, June 2, 2015, st-anton <notifications@github.com> wrote:

> Ups, suddenly during the test session it is there !??!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/580#issuecomment-108076294>
> .
>


-- 
Sent from Gmail Mobile

**Comment by st-anton** [comment]
I think different of the images folder (also see #582 and https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/536#issuecomment-94198309):
The folder is set up during install, the images needed for media (speaker, pdf, video, textfile...) is copied into it. Then user may upload his own images into it. During save of study, serie, media and so on, more and more images will be add.

**Comment by bcordis** [comment]
I was seeing there was no option to select existing media images so I will update that ASAP.

**Comment by st-anton** [comment]
Works well
