### ISSUE TITLE
Frontend and Backend new / edit media: Filesize is not saved

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#584]
db entry params -> "size" is always 0

**Comment by bcordis** [comment]
This is do to it can't find the media.

On Tuesday, June 2, 2015, st-anton <notifications@github.com> wrote:

> db entry params -> "size" is always 0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/584>.
>


-- 
Sent from Gmail Mobile

**Comment by bcordis** [comment]
@st-anton Can you check to see if your media is properly available to the server? Like look at the path and see if you can see it through the browser.

**Comment by bcordis** [comment]
@tomfuller2 Can you also try testing this?

**Comment by tomfuller2** [comment]
Need to put in an override if user has put in a value in filesize.

**Comment by bcordis** [comment]
@st-anton Should be fixed now.

**Comment by st-anton** [comment]
I can fill in the filesize in the backend. Frontend not yet tested.
