### ISSUE TITLE
Export of templatecode tables broken in 8.08

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#585]
When I've tried to import an 8.08 db I get an error about the templatecode table. 

In the backup it appears like this:
--
-- Dumping data for table `s6hej_bsms_templatecode`
--

INSERT INTO `s6hej_bsms_templatecode` SET ;
INSERT INTO `s6hej_bsms_templatecode` SET ;
INSERT INTO `s6hej_bsms_templatecode` SET ;
INSERT INTO `s6hej_bsms_templatecode` SET ;

Can you look into why it's not exporting correctly?

**Comment by tomfuller2** [comment]
Here is the contents of the table as it is on my church site:

INSERT INTO `jos_bsms_templatecode` (`id`, `published`, `type`, `filename`, `asset_id`, `templatecode`) VALUES
(1, 1, 1, 'fluidsermonlist', 6272, '<?php\r\n\r\n/**\r\n * Helper for Template Code\r\n *\r\n * @package    BibleStudy.Admin\r\n * $author		Tom Fuller www.CalvaryChapelNewberg.org\r\n * @copyright  (C) 2007 - 2013 Joomla Bible Study Team All rights reserved\r\n * @license    http://www.gnu.org/copyleft/gpl.html GNU/GPL\r\n * @link       http://www.JoomlaBibleStudy.org\r\n * */\r\n// No Direct Access\r\ndefined(''_JEXEC'') or die;\r\n\r\n// Do not remove\r\n?>\r\n\r\n  \r\n  <div class="row-fluid span12">\r\n    <h2>\r\n      Bible Studies\r\n    </h2>\r\n  </div>\r\n\r\n  \r\n\r\n  <div class="row-fluid span12">\r\n    <?php echo $this->page->gobutton;\r\n    echo $this->limitbox;\r\n	echo $this->page->popular;\r\n    echo $this->page->books;\r\n    echo $this->page->teachers;\r\n    echo $this->page->series;\r\n    echo $this->page->years;\r\n    echo $this->page->order;\r\n    $oddeven = '''';\r\n	$class1 = ''#d3d3d3'';\r\n    $class2 = '''';?>\r\n  </div>\r\n  <?php foreach ($this->items as $study)\r\n    {\r\n      $oddeven = ($oddeven == $class1) ? $class2 : $class1;\r\n      ?>\r\n  <div class="row-fluid span12">\r\n    <div class="span3">\r\n    \r\n   <strong> <?php echo $study->scripture1;?></strong>\r\n  </div>\r\n  <div class="span4">\r\n    <a href="<?php echo $study->detailslink;?>"><strong><?php echo $study->studytitle;?></strong></a>\r\n  </div>\r\n  <div class="span4">\r\n    <?php echo $study->media;?>\r\n  </div>\r\n    <div class="span12" style="margin-left: -2px;">\r\n    <p><?php echo $study->studyintro;?></p>\r\n  </div>\r\n    <hr class="span12" style="border: 0; height: 1px; background-image: -webkit-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0)); background-image: -moz-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0)); background-image: -ms-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0)); background-image: -o-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));" />\r\n  </div>\r\n   <?php }?>\r\n  <div class="row-fluid span12 pagination">\r\n    <?php echo $this->pagination->getPageslinks();?>\r\n  </div>\r\n\r\n'),
(2, 1, 7, 'fluidmodule', 6273, '<?php\r\n\r\n/**\r\n * Helper for Template Code\r\n *\r\n * @package    BibleStudy.Admin\r\n * @copyright  (C) 2007 - 2013 Joomla Bible Study Team All rights reserved\r\n * @license    http://www.gnu.org/copyleft/gpl.html GNU/GPL\r\n * @link       http://www.JoomlaBibleStudy.org\r\n * */\r\n// No Direct Access\r\ndefined(''_JEXEC'') or die;\r\n\r\n// Do not remove\r\n\r\n foreach ($list as $study)\r\n    {\r\n      \r\n      ?>\r\n<div class="row-fluid span12" >\r\n \r\n  <div class="span6">\r\n    <a href="<?php echo $study->detailslink;?>"><strong><?php echo $study->studytitle;?></strong></a>\r\n  </div>\r\n  <div class="span6">\r\n    <?php echo $study->media;?>\r\n  </div>\r\n \r\n  </div>\r\n   <?php }?>\r\n<div span12>\r\n  <?php echo $link;?>\r\n</div>'),
(3, 1, 2, 'fluidsermondetail', 6274, '<?php\r\n\r\n/**\r\n * Helper for Template Code\r\n *\r\n * @package    BibleStudy.Admin\r\n * @copyright  (C) 2007 - 2013 Joomla Bible Study Team All rights reserved\r\n * @license    http://www.gnu.org/copyleft/gpl.html GNU/GPL\r\n * @link       http://www.JoomlaBibleStudy.org\r\n * */\r\n// No Direct Access\r\ndefined(''_JEXEC'') or die;\r\n\r\n// Do not remove\r\n\r\n?>\r\n<div class="container-fluid">\r\n  \r\n\r\n<div class="row-fluid">\r\n<div class="span12">\r\n   <h3 style="text-align:right;">\r\n  Bible Study from Calvary Chapel Newberg\r\n</h3>\r\n</div> \r\n<div class="span12"> \r\n  <h4 style="text-align:right;">\r\n  with <?php echo $this->item->teachername;?>\r\n</h4>\r\n  </div>\r\n</div>\r\n<?php\r\necho $this->print;\r\necho $this->page->social;\r\necho $this->related;\r\n?>\r\n<br />\r\n<h2 style="text-align:center;">\r\n  <?php echo $this->item->studytitle;?>\r\n</h2>\r\n<h4 style="text-align:center;">\r\n<strong><?php echo $this->item->scripture1;?></strong></h4>\r\n<?php echo $this->item->media;?>\r\n<p>\r\n  <?php echo $this->item->studytext;?>\r\n</p>\r\n</div>'),
(4, 1, 7, 'latestmodule', 6534, '<?php\r\n\r\n/**\r\n * Helper for Template Code\r\n *\r\n * @package    BibleStudy.Admin\r\n * @copyright  (C) 2007 - 2013 Joomla Bible Study Team All rights reserved\r\n * @license    http://www.gnu.org/copyleft/gpl.html GNU/GPL\r\n * @link       http://www.JoomlaBibleStudy.org\r\n * */\r\n// No Direct Access\r\ndefined(''_JEXEC'') or die;\r\n\r\n// Do not remove\r\nforeach ($list as $study)\r\n    {\r\n      \r\n      ?>\r\n<div class="row-fluid span12" >\r\n \r\n  <div class="span12">\r\n    <a href="<?php echo $study->detailslink;?>"><strong><?php echo $study->studytitle;?></strong></a>\r\n  \r\n  </div>\r\n <div class="span10">\r\n    <p style="color:black; font-family: arial;">\r\n      <?php echo $study->studyintro;?>\r\n    </p>\r\n  </div>\r\n  <div class="span10" style="color:black; font-family: arial;">\r\n    <strong><?php echo $study->scripture1;?></strong><?php if ($study->series_text){ ?> - As part of our series: "<?php echo $study->series_text;?>"<?php } ?> with <?php echo $study->teachertitle.'' ''.$study->teachername;?>.\r\n  </div>\r\n</div>\r\n   <?php }?>\r\n\r\n');

**Comment by bcordis** [comment]
Can you tell me if you updated your export lib to the same as the 8.x version there is a bug that I have fixed in 8.0.8

**Comment by tomfuller2** [comment]
Yes - I'm using 8.08

**Comment by bcordis** [comment]
There is a 8.0.9 version out now. But not released.

**Comment by bcordis** [comment]
I still need to look at see if we are using the same export code. This would help.

**Comment by bcordis** [comment]
Moving to Core export db.
