### ISSUE TITLE
Full server path and filesize not working on all files from previous version

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#586]
Using the June 3 code, I created a site: www.joomlaoregon.org/jbs that had JBS 8.08, imported my current church db, then installed JBS 9. 
The install went well with no errors. 
Embed code (YouTube) plays
mp3 files do not. The proper server is selected but only the final path is being used, not the website.
So instead of: www.calvarynewberg.net/MediaFiles/2015/2015-018.mp3 it appears to just try to load: /MediaFiles/2015/2015-018.mp3 

Also: Filesize is not importing.

**Comment by tomfuller2** [comment]
A dump of $media produced by getMediaRows2() in site/helper/media.php gives us:


Application: site

Lock Window Refresh Close Window Expand all Collapse all

    [stdClass object] (unknown name) Tooltip
        Properties
            [string] access = "1"
            [string] asset_id = "32624"
            [string] booknumber = "142"
            [string] chapter_begin = "1"
            [string] chapter_end = "1"
            [string] checked_out = "385"
            [string] checked_out_time = "2015-06-09 16:50:34"
            [string] comment = ""
            [string] created_by = "0"
            [string] created_by_alias = ""
            [string] createdate = "2015-05-31 17:00:34"
            [string] downloads = "51"
            [string] hits = "0"
            [string] id = "3006"
            [string] image = ""
            [string] language = "*"
            [string] media_hours = ""
            [string] media_minutes = "42"
            [string] media_seconds = "10"
            [string] metadata = "{}"
            [string] modified = "0000-00-00 00:00:00"
            [string] modified_by = "0"
            [string] ordering = "0"
            [string] params = "{"link_type":"1","docMan_id":"0","article_id":"-1","virtueMart_id":"0","player":"1","popup":"1","mediacode":"","filename":"\/MediaFiles\/2015\/2015-01..." (Length = 386)
            [string] plays = "10"
            [string] podcast_id = "1"
            [string] published = "1"
            [string] series_id = "14"
            [string] series_text = "Who Is This Man? - Luke's Gospel"
            [string] series_thumbnail = ""
            [string] seriesid = "14"
            [string] server_id = "6"
            [string] sid = "957"
            [string] sparams = "{"path":"www.calvarychapelnewberg.net"}"
            [string] spath = "www.calvarychapelnewberg.net"
            [string] study_id = "957"
            [string] studydate = "2015-05-31 17:00:34"
            [string] studyintro = "How often do we react badly when the going gets rough? We can take a lesson from a 12-14 year old girl named Mary. When presented with the presence of..." (Length = 262)
            [string] studytitle = "The Amazing Open-Hearted Mary"
            [string] teacher_id = "1"
            [string] teacher_image = "images/DSC_0252_cropped_385.jpg"
            [string] teacher_thumbnail = "images/DSC_0252_cropped_80x80.jpg"
            [string] teachername = "Tom Fuller"
            [string] thumb = ""
            [string] tid = "1"
            [string] verse_begin = "26"
            [string] verse_end = "38"

So it looks like we need to put sparams together with spath

**Comment by tomfuller2** [comment]
So now I'm sure what's wrong. The popup gets the proper path: spath + params->filename.

and in the page source of the popup here is the filename: 'file': 'http://www.calvarychapelnewberg.net/MediaFiles/2015/2015-018.mp3',;

But only the filename as text (which I had in the params so that's okay) shows up, but no file plays or shows up as in icon.

**Comment by bcordis** [comment]
@tomfuller2 Fixed do to ; in jqplayer code.

**Comment by tomfuller2** [comment]
Works now!
