### ISSUE TITLE
Backend new media: Addon language cannot be loaded

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#590]
Right after clicking on 'new', the message appears:
An error has occurred. 0 Addon language could not be loaded

**Comment by bcordis** [comment]
Can you retest this. I'm not able to reproduce this on a clean install. Also put down steups that you took after task=admin.dbreset to get the error.

**Comment by bcordis** [comment]
@st-anton @tomfuller2 @genu This is do to the default server not being set in admin. Will need to find a fix for this on new install and on migration.

**Comment by bcordis** [comment]
This will be fixed on setting defaults for new install and for migration. Closing as this is in migration and will be set on final creation of defaults.

**Comment by st-anton** [comment]
Works as expected
