### ISSUE TITLE
Installation aborts

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#594]
Installation on a fresh Joomla 3.4.1 aborts with 'warning', but in fact it aborts:

Table 'fmnj34_bsms_admin' already exists SQL=CREATE TABLE `fmnj34_bsms_admin` ( `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT, `drop_tables` INT(3) DEFAULT '0', `params` TEXT, `asset_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'FK to the #__assets table.', `access` INT(10) UNSIGNED NOT NULL DEFAULT '0', `installstate` TEXT, `debug` TINYINT(3) NOT NULL DEFAULT '0', PRIMARY KEY (`id`), KEY `idx_access` (`access`) ) ENGINE = InnoDB DEFAULT CHARSET = utf8;

**Comment by bcordis** [comment]
Fixed.

**Comment by st-anton** [comment]
Fixed -> OK
