### ISSUE TITLE
Backend Thumbnail creation: teacher overwrites study and vice versa

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#596]
Teachers thumbnails are stored in folder `\images\biblestudy\studies\<ID>`
This folder is also used for studies thumbnails. If a study thumbnail is present, and a teacher with - by chance - the same ID number is created, then the former thumbnail is deleted and the second is stored.

My opinion: Teachers images should be stored in `\images\biblestudy\teachers\thumb`, studies images should be stored in `\images\biblestudy\studies\thumb` and so on.
Also I don't understand the creation of the folder ID: Every teacher (one thumbnail) gets an extra folder. Is there a reason? If it is needed to identify the thumbnail, can't it be the image name (like: `\images\biblestudy\teachers\thumb\12.jpg`)?

**Comment by bcordis** [comment]
This was set up by @genu and me and I think your suggestion is getter. I do see your point on the folder for the teachers to be stored in a different folder. 

For scripting i could see the thumb folder working better.

**Comment by bcordis** [comment]
@st-anton folder ID are to separate the images but are not needed if we add a id onto the file name.

**Comment by bcordis** [comment]
@st-anton Only place we use it is thumbnails. and we only specify the folder at thumbnail creation not where the user selects the image from.

What you think @tomfuller2 ?

**Comment by tomfuller2** [comment]
I think Anton's suggestion is good. Let's go with that!

**Comment by bcordis** [comment]
@tomfuller2 This should be working now. Need more testing.

**Comment by bcordis** [comment]
Closing as this was tested in other bug.
