### ISSUE TITLE
Frontend new study: Notice 'Undefined variable: book'

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#597]
In the books tab, a notice appears:
Notice: Undefined variable: book in \components\com_biblestudy\views\messageform\tmpl\edit.php on line 148

**Comment by bcordis** [comment]
@st-anton Can you explain the URL you are using to reproduce this as I'm not formeler with a books tap?

**Comment by bcordis** [comment]
found the error do to miss labeled variable
