### ISSUE TITLE
Backend media upload: File is stored in images folder

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#598]
I test on a local xampp installation - not a server. But I don't guess, that is is caused by this:
My server is on a remote url location - let me say: www.mystudystorage.org . Trying to upload a media file to this server copies the file into the \images\biblestudy\media folder, not on the foreign url.

By the way: Can a file be uploaded to a foreign server at all?

**Comment by bcordis** [comment]
We do not support foreign server upload right now. Only local server.

On Monday, August 17, 2015, st-anton <notifications@github.com> wrote:

> I test on a local xampp installation - not a server. But I don't guess,
> that is is caused by this:
> My server is on a remote url location - let me say: www.mystudystorage.org
> . Trying to upload a media file to this server copies the file into the
> \images\biblestudy\media folder, not on the foreign url.
>
> By the way: Can a file be uploaded to a foreign server at all?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/598>.
>


-- 
Sent from Gmail Mobile

**Comment by bcordis** [comment]
@st-anton Can we lower this bug as it is not a critical bug more of a limit that needs to be set in legacy server?

**Comment by bcordis** [comment]
I have updated this bug as it is trivial and does not brake the function of the system. It is documented that the uploader only uploads to the local server. I'll leave the issue open for further development.

**Comment by tomfuller2** [comment]
Let's go ahead and close this as I think it's okay for the file to upload to the images folder. Seems to work fine.
