### ISSUE TITLE
Migration from JBS 8.0.0 crashes: 'Unknown column podcast'

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#599]
1054 Unknown column 'podcast' in 'field list' SQL=UPDATE `fmnj34_bsms_admin` SET `podcast`=NULL,`series`=NULL,`study`=NULL,`teacher`=NULL,`media`=NULL,`params`='{\"metakey\":\"\",\"metadesc\":\"\",\"compat_mode\":\"1\",\"jbsmigrationshow\":\"0\",\"studylistlimit\":\"10\",\"show_location_media\":\"0\",\"popular_limit\":\"\",\"character_filter\":\"1\",\"format_popular\":\"0\",\"socialnetworking\":\"0\",\"sharetype\":\"1\",\"default_main_image\":\"\",\"default_series_image\":\"\",\"default_teacher_image\":\"\",\"default_download_image\":\"\",\"default_showHide_image\":\"\",\"location_id\":\"1\",\"teacher_id\":\"9\",\"series_id\":\"-1\",\"booknumber\":\"-1\",\"messagetype\":\"1\",\"default_study_image\":\"\",\"download\":\"1\",\"target\":\"_blank\",\"server\":7,\"path\":\"2\",\"podcast\":[\"-1\"],\"media_image\":\"2\",\"mime\":\"1\",\"from\":\"x\",\"to\":\"x\",\"pFrom\":\"x\",\"pTo\":\"x\"}',`download`=NULL,`main`=NULL,`showhide`=NULL,`drop_tables`='0',`access`='1',`installstate`=NULL,`debug`='0' WHERE `id`='1'

**Comment by st-anton** [comment]
It seems, that (most of) the imported data are present.

**Comment by bcordis** [comment]
@st-anton Can you send me the DB that you are using to test with for migration? or the steps you used to reproduce this error.

**Comment by bcordis** [comment]
@st-anton Found it in the table folder. we still had the old columns stated.

**Comment by bcordis** [comment]
@st-anton @tomfuller2  Fixed.

**Comment by st-anton** [comment]
Tested ok
