### ISSUE TITLE
Latest package has failure in displaying media

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#600]
Fatal error: Class 'JHtmlJwplayer' not found in /home1/joomlaor/public_html/joomlaoregon_com/jbs/components/com_biblestudy/helpers/media.php on line 292

This comes from any view that is trying to show media files. 

This is for inline playing, here is the place where it is accessed in media.php:
case 2: // Inline
						JHtmlJwplayer::framework();
						$playercode = JHtmlJwplayer::render($media, $media->id, $params);
						break;

See this happening at: http://joomlaoregon.com/jbs/index.php/studies-list

**Comment by bcordis** [comment]
Can you verify that jwplayer.php is present?

**Comment by tomfuller2** [comment]
It is, under Media/com_biblestudy/player

**Comment by bcordis** [comment]
No it should be under admin->helpers->http->jwplayer.php

On Tuesday, September 1, 2015, Tom Fuller <notifications@github.com> wrote:

> It is, under Media/com_biblestudy/player
>
> On Tue, Sep 1, 2015 at 5:03 AM, Brent Cordis <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Can you verify that jwplayer.php is present?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/600#issuecomment-136688648
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/600#issuecomment-136801215>
> .
>


-- 
Sent from Gmail Mobile

**Comment by tomfuller2** [comment]
Yep. It's there.

**Comment by tomfuller2** [comment]
So I notice that this is the only place in the $media file that we use this code. Is this what we want to do? What is expected here to happen?
