### ISSUE TITLE
Adding new media problems

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#603]
Adding a new media file from within a study.
Upload works. When picking an image for the filetype it goes to the images/biblestudy folder but there are no images to choose from. We need to have the same stock of images that come with the component already loaded there.
I uploaded an mp3 file to use the internal player.
When I tried to play it, I get this error in the popup:

Fatal error: Cannot access protected property BiblestudyViewPopup::$params in /home1/joomlaor/public_html/joomlaoregon_com/jbs/administrator/components/com_biblestudy/helpers/html/jwplayer.php on line 101

See it on the last media file (a CD icon) on the www.joomlaoregon.com/jbs site.

**Comment by bcordis** [comment]
Well I fixed the params problem and checked the salty check again as it was not a working right.  This should work right from standard view also.

**Comment by tomfuller2** [comment]
When I upload a file using a local server, the site does not tell me the path to the file - shouldn't this be filled in upon upload?
Also - it appears that upon migration all servers are set to default but there is no information in the default server.

**Comment by bcordis** [comment]
They should not be all pointed to the default server.

**Comment by bcordis** [comment]
If you do a install it should copy the images to the new folder.

**Comment by tomfuller2** [comment]
Go to the admin of the JBS site and add a new media file using the JBS server. When you upload it - it does not appear to upload (the file is not there under images/com_biblestudy/media) though the page shows it did upload - however, the upload path is not filled in and the form won't save. The admin shouldn't have to enter an upload path for a file uploaded to a local server type.

**Comment by tomfuller2** [comment]
In what file is the copying of the images happening because it didn't happen on the JBS test site. I don't see it in the xml file or the biblestudy script file.

**Comment by tomfuller2** [comment]
I also notice that in the migration we change the image path to media/com_biblestudy/images - yet that is unreachable by the admin for changing the image. Would it be better to have the images migrated to images/com_biblestudy instead?

**Comment by bcordis** [comment]
That is not good need to change that back to the other folder if we move the files.

**Comment by bcordis** [comment]
It is in the postflight section and right now it only happens in install. I'm looking at another way to check if files have been copied.

**Comment by tomfuller2** [comment]
Okay

**Comment by tomfuller2** [comment]
Upon fresh install the images are NOT copied to the images/biblestudy folder.

**Comment by bcordis** [comment]
@tomfuller2 this should be working now.

**Comment by tomfuller2** [comment]
Works
