### ISSUE TITLE
Need to add media images to images folder

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#604]
Since we now require admins to get the images/biblestudy folder when adding an image to a media file, we need to load the images in the com_biblestudy folder that we used to provide as a drop down.

**Comment by bcordis** [comment]
This is in the install script.

**Comment by bcordis** [comment]
used in #603

**Comment by bcordis** [comment]
also in a3096da4e2c199ae1ed860b53c7f1e5326ab33b9

**Comment by bcordis** [comment]
@tomfuller2 retest pleas fixed the problem.
