### ISSUE TITLE
Old code usage on mod_biblestudy

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Joomla-Bible-Study#606]
Line 46 on mod_biblestudy.php is broken and need a fix.

**Comment by tomfuller2** [comment]
I'll look at it

**Comment by tomfuller2** [comment]
Fixed and closed https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/41c558b1c4fe8474a21c9a34dd86e205f6fb6a14
