### ISSUE TITLE
Filesize is not being done correctly

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#609]
Not sure exactly why we moved away from the last version of the filesize - putting it into a legacy server field and all - but it's not working. Try to manually add a filesize in a mediafile - it says fileConverter1() is not defined.

**Comment by tomfuller2** [comment]
I managed to get the popup to appear. Joomla's API changed in 3 so that in the filesize.php file we have to give a full path to the js. BUT - the value from the popup doesn't get back into the form. https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/bc9c3ee6293e373289614f37e09262406c653700

**Comment by bcordis** [comment]
Looks like i need to update the JS. I'll look into it ASAP.

**Comment by bcordis** [comment]
@tomfuller2 Can you look at this and verify it is working now?

**Comment by tomfuller2** [comment]
Working now. What did you do?

**Comment by bcordis** [comment]
In the new way it pointed to the folder it was not correct and also the
name of the imput was different. Will need to look at converting this in a
new release.

On Friday, October 9, 2015, Tom Fuller <notifications@github.com> wrote:

> Closed #609
> <https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/609>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/609#event-431556682>
> .
>


-- 
Sent from Gmail Mobile
