### ISSUE TITLE
Want to remove Share view

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#613]
I would rather we just use ShareIt. Okay to remove our internal social network share?

**Comment by bcordis** [comment]
Yes that sounds good. Yes

On Saturday, October 24, 2015, Tom Fuller <notifications@github.com> wrote:

> I would rather we just use ShareIt. Okay to remove our internal social
> network share?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/613>.
>


-- 
Sent from Gmail Mobile

**Comment by tomfuller2** [comment]
This is done. Removed code and files.
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/356a62387f717aef9ece84e8f131c7789473cc97
