### ISSUE TITLE
YouTube add on

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Joomla-Bible-Study#615]

**Comment by bcordis** [comment]
@tomfuller2 Now should be working right. Please test new server.

**Comment by tomfuller2** [comment]
It does work but I get this error:
Notice: Undefined property: BiblestudyViewPopup::$length in /home1/joomlaor/public_html/joomlaoregon_com/jbs/components/com_biblestudy/views/popup/view.html.php on line 221

I'm clicking on YouTube from this study: http://joomlaoregon.com/jbs/index.php/studies-list/sermon/956-an-open-and-shut-mind/1

**Comment by tomfuller2** [comment]
Did not get the full pull. This problem isn't there.
