### ISSUE TITLE
Missing Bible2015 icon.

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Joomla-Bible-Study#616]

**Comment by tomfuller2** [comment]
What do you mean? What exactly is missing and where can I see it missing?

**Comment by bcordis** [comment]
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/blob/development/com_biblestudy/admin/views/cpanel/tmpl/default.php line 35
src="../media/com_biblestudy/images/bible2015.png"

file is missing in the media folder on github.

**Comment by tomfuller2** [comment]
Fixed https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/b19ff56b2a47a04f4512ac93848ec087ef622bee
