### ISSUE TITLE
Menue item setup 'Single Serie': Serie selection is not a popup and does not work

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#621]
Tested with 900beta1:
Setting up a new menue item 'Single Series', the selection of the series is not a popup. Selecting the serie does not react, so the serie is not selectable.

**Comment by tomfuller2** [comment]
This one is really stumping me. Something is clearly wrong - the modal is opening up full screen, not as a modal but I've compared the studydetails and nothing seems to be missing or different.

**Comment by bcordis** [comment]
Are we leading the Css right?

On Wednesday, February 17, 2016, Tom Fuller <notifications@github.com>
wrote:

> This one is really stumping me. Something is clearly wrong - the modal is
> opening up full screen, not as a modal but I've compared the studydetails
> and nothing seems to be missing or different.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/621#issuecomment-185533754>
> .
>


-- 
Sent from Gmail Mobile

**Comment by tomfuller2** [comment]
We do: JHTML::_('stylesheet', 'system/modal.css', array(), true); (line 42 of admin/models/fields/modal/seriesdetail.php

**Comment by tomfuller2** [comment]
This is fixed. Missing modal behavior JHTML declaration.
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/ae4b24c0965278c0758dee2bcdac5b6c9722d6c4
