### ISSUE TITLE
Migration sets no assets on studytopics while edit does

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#623]
tested with 900beta1
Migration of a 800 database generates asset_id=0, adding a new studytopic with 900 adds assit_id other than 0. Example: 
`INSERT INTO fmnj34_bsms_studytopics (id, study_id, topic_id, asset_id, access) VALUES`
`(1, 288, 16, 0, 1),`
`(5, 286, 17, 774, 1),`

Sidenote: Checking the assets does not complain about asset_id=0 here.

**Comment by bcordis** [comment]
This is fixed in beta3 please retest.
