### ISSUE TITLE
Landing page: missing div results in too much /div

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#624]
tested with 900beta1
The landing page encloses each item (year, series, topic ect.) with
`<div class="span2"><a href="...shortened...">5. Mose (Deuteronomium)</a></div>`
The leading `<div class="span2">` is missing at the teachers. This results in broken layout.

**Comment by tomfuller2** [comment]
Is there any way you can figure out what line the error is on in site/helpers/landing.php? I didn't create this and tried my best to make it responsive but it's a bear!

**Comment by tomfuller2** [comment]
I think I've fixed this. https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/16f75eb925a1b30d8d4f1d8d1db250fa8b43d0bb
