### ISSUE TITLE
seriesGetelement Removed function

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Joomla-Bible-Study#642]
Function no longer available need to replace.
$element       = $this->seriesGetelement($r, $row, $customelement, $custom, $islink, $params, $view = null);

file: site/helpers/serieslist.php

**Comment by tomfuller2** [comment]
Checked for usages of the function. None found. Removed.
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/485987a90af189178715dfc720d673f7e16ea21a
