### ISSUE TITLE
getSeriesstudiesDBO removed function

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Joomla-Bible-Study#643]
$items   = $this->getSeriesstudiesDBO($id, $params, $limit);

file: site/helpers/serieslist.php

**Comment by tomfuller2** [comment]
I added back in a function but needs to be tested

https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/07fbf4411206a7999d0ca66985ac62681392aa96

**Comment by bcordis** [comment]
Looking over the code so fare it looks good but need to verify what we moved into params. I'll look more tonight.
