### ISSUE TITLE
Custom View Mod_Biblestudy

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Joomla-Bible-Study#644]
getHeader function no longer existe need to find replacement.

**Comment by tomfuller2** [comment]
I have removed expert mode and migrated existing expert mode content to templatefiles. Needed to add a script to the module install routine.
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/e4c1471212235161e94be63ef618fedd67189aa3
