### ISSUE TITLE
_Blank declaration not followed in some media files

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#647]
If a media file is listed as Direct Inline, there is no target in the html. Not sure where this is pulling from now that we've switched the way of doing servers. Check the newsite under one of the pdf's

**Comment by bcordis** [comment]
Can you point me to the record the is having this trundle as I see in the media creation for direct link it is there.

**Comment by bcordis** [comment]
@tomfuller2 Now it should be fixed. I have tested locally.

**Comment by tomfuller2** [comment]
Did you by chance test this? It still seems the growth group questions opens in the same window.

**Comment by bcordis** [comment]
I only tested on my box you will need to update your code on the website media.php file.
