### ISSUE TITLE
Some images not coming through migration

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#648]
The path for the growth group questions image did not come through the migration. It's blank. Check out any of the growth group question media files on /newsite.

**Comment by tomfuller2** [comment]
Tried to fix but needs to be tested.
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/24707e7f178084e461ce7e627fdce896bd225d05

**Comment by bcordis** [comment]
Ok I'll try and test it also.

**Comment by tomfuller2** [comment]
This has been fixed: https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/797ce34489785a93311fef5c5e0017db2c80437c
