### ISSUE TITLE
Hover text on media files doesn't reflect the mime type

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#652]

**Comment by bcordis** [comment]
@tomfuller2 Can you send me example links. Having trouble finding the hover info?

**Comment by tomfuller2** [comment]
Look at the studies list example on the JBS site and hover your mouse over the media files. Except for the pdf leaf - all of them just say "Audio"

**Comment by bcordis** [comment]
That text comes from the media file edit page 

![image](https://cloud.githubusercontent.com/assets/994259/16273145/27edc594-3866-11e6-91aa-c0dd39afe33c.png)

**Comment by tomfuller2** [comment]
Ah - that's unexpected. The button text was designed to put actual text on top of the button if they chose that option. We'll need to explain that somewhere I guess.

**Comment by bcordis** [comment]
We don't have w conversion from mine to text so the best place I could pull from is there.

**Comment by bcordis** [comment]
Closing as know behavior change.
