### ISSUE TITLE
Module doesn't pull in icon for default download icon

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Joomla-Bible-Study#669]
It only shows the default image.

**Comment by bcordis** [comment]
@tomfuller2 Are you working on this?

**Comment by tomfuller2** [comment]
I'll need some help on this.

I believe what is happening is that module is not getting the admin param to use the icon.

In the mod_biblestudy.php file it is getting admin params on line 36. That's merged and then in the default_main.php it is used to call the listing on line 34. 

So then listing asks for the media image from /helpers/media.php and on line 194 looks to see what parameter has been set. It defaults to the image.

I noticed that we don't do the merging of admin params the same way in the sermons view. Perhaps we just need to bring that into the module? But I don't know how you did that.

**Comment by bcordis** [comment]
@tomfuller2 making pull request as there are some more errors that could happen with the model.  I'm looking to see the default icon params will pass.
