### ISSUE TITLE
Move time for media out of overall study

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Joomla-Bible-Study#687]
Move time constants form study to each media file for video and audio only.

**Comment by tomfuller2** [comment]
Agreed. Sometimes my video length is not the same as audio. Maybe media
file overrides study time?

**Comment by bcordis** [comment]
In a way deprecate the sermon fields and point to the media and then we can drop it in 9.2

**Comment by tomfuller2** [comment]
Migrate current time to media too

**Comment by bcordis** [comment]
Removed all to gether.
