### ISSUE TITLE
add-on language error when trying to add new files

### ISSUE THREAD

**Issue by jrockman13** [Joomla-Bible-Study/Joomla-Bible-Study#699]
So, this is very odd. Sunday/Monday I was able to add some additional media files. Now, when I try to add a new file, I get the same "language add-on could not be loaded error." It happens when I click "New" on the media file section or on the "add media file" inside a study.

**Comment by bcordis** [comment]
@tomfuller2 Look at this fix. I've tested this and it work great if they have some bug in not setting or changing the default server (Administration->Default Settings->Server). This will also allow them to load media even if the server was not set right. By doing this if the migration failed then they still will have some problems as the view will load but there will be no indication that the DB is not migrated correctly.

Let me know what you think. I'm having @jrockman13 test this out on his website as it cam up.

**Comment by jrockman13** [comment]
I tested the commit, and it allows me to get past the "addon language error" and create a media file. As soon as I select a server, things are good. Thanks!

**Comment by bcordis** [comment]
Great to here this will be out in v9.0.5
