### ISSUE TITLE
Youtube Server URLS in podcast

### ISSUE THREAD

**Issue by jrockman13** [Joomla-Bible-Study/Joomla-Bible-Study#700]
Okay, so my feed won't validate with youtube videos in it.

The old studies, using the legacy mode of youtube, are fine. The new URLS have an issue:

First, I tried copy/pasting the entire "share" url: "https://youtu.be/videoid"
That results in a feed with URLS that look like this: "http://https://youtu.be/videoid"

Then I delete the "https://" thinking that would fix it. Nope.
Feed writes like this "http:///youtu.be/videoid" Note the extra slash.

So, any other ideas?

**Comment by tomfuller2** [comment]
Did you try pasting the entry from Share in youtube? Not the shortened one

**Comment by jrockman13** [comment]
I used the shortened link per Brent's instructions. I can try the full link.

On Sep 19, 2016 8:14 PM, Tom Fuller <notifications@github.com> wrote:

Did you try pasting the entry from Share in youtube? Not the shortened one

**Comment by jrockman13** [comment]
Also, it works fine on the site in the player, it just doesn't work in the podcast feed

On Sep 19, 2016 8:15 PM, Josiah Rocke <jrocke@cbcneenah.org> wrote:

I used the shortened link per Brent's instructions. I can try the full link.

On Sep 19, 2016 8:14 PM, Tom Fuller <notifications@github.com> wrote:

Did you try pasting the entry from Share in youtube? Not the shortened one

**Comment by tomfuller2** [comment]
Oh I see. Yes Brent was right. Use the shortened one. YouTube videos won't
work in a podcast. Podcasts are for downloading and playing files, not
streaming them. Have you been using the podcast for this before?

**Comment by jrockman13** [comment]
Yes. It works fine on Android.

On Sep 19, 2016 8:25 PM, Tom Fuller <notifications@github.com> wrote:
Oh I see. Yes Brent was right. Use the shortened one. YouTube videos won't
work in a podcast. Podcasts are for downloading and playing files, not
streaming them. Have you been using the podcast for this before?

**Comment by bcordis** [comment]
With the new version coming out I have fixed the URL formation. We support all share urls and full URL.

**Comment by jrockman13** [comment]
Ok, so maybe it would be better to just remove them from the podcast?

On Sep 19, 2016 8:25 PM, Tom Fuller <notifications@github.com> wrote:
Oh I see. Yes Brent was right. Use the shortened one. YouTube videos won't
work in a podcast. Podcasts are for downloading and playing files, not
streaming them. Have you been using the podcast for this before?

**Comment by bcordis** [comment]
YouTube is not supported in podcast. We don't have it filtered out yet.

**Comment by bcordis** [comment]
This Should be fixed in v9.0.5 @jrockman13 Let me know if it is not?
