### ISSUE TITLE
Uploader naming error.

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Joomla-Bible-Study#709]
using JBSM upholder the system would wrongly produce the filename.

**Comment by bcordis** [comment]
Fixed and in place now.

**Comment by bcordis** [comment]
@tomfuller2 Please Review.

**Comment by tomfuller2** [comment]
I  tried using the uploader on my localhost and it did not work. No file uploaded and filename was not saved in the record

**Comment by bcordis** [comment]
System did not show error of file size. Will look into that latter as different problem.
