### ISSUE TITLE
Add striper for server name to remove http or https

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Joomla-Bible-Study#710]
remove everything before //

**Comment by bcordis** [comment]
@tomfuller2 please review.

**Comment by tomfuller2** [comment]
I'm confused as to why we need this. So you add // to the beginning of each server path? Won't that break it?

**Comment by bcordis** [comment]
No it will not brake the URL. browser us // as a generic handle. this allow for http or https traffic.
