### ISSUE TITLE
Error decoding JSON data: Syntax error 

### ISSUE THREAD

**Issue by jrockman13** [Joomla-Bible-Study/Joomla-Bible-Study#719]
xposted: http://www.joomlabiblestudy.org/index.php?option=com_kunena&view=topic&catid=35&id=3734&Itemid=812#4484

**Comment by jrockman13** [comment]
anyone had a chance to look at this?

**Comment by jrockman13** [comment]
Update: posted new thread in correct forum: http://www.joomlabiblestudy.org/index.php?option=com_kunena&view=topic&catid=39&id=3735&Itemid=812#4488

**Comment by bcordis** [comment]
Need a db backup to test bug. As right now can't reproduce the bug.

**Comment by jrockman13** [comment]
Can I post it on Github or should I share a google drive link?

**Comment by bcordis** [comment]
I would send a director linked on the ticket so I can look download the db. Not sure how big it is. Plus for privacy.

**Comment by bcordis** [comment]
Please replace this file ASAP.

https://github.com/joomla/joomla-cms/blob/staging/libraries/vendor/joomla/registry/src/Format/Json.php

This will fix the problem for you. It is coming out next versions of Joomla

**Comment by bcordis** [comment]
Also I have made some corrections to our scripts.

https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/pull/720

I have tested it on your db and it corrects all the errors in your json params.

Let me know if you have trouble with this.
