### ISSUE TITLE
Legacy server not appending url to xml file

### ISSUE THREAD

**Issue by jrockman13** [Joomla-Bible-Study/Joomla-Bible-Study#722]
Having an issue with our xml file. We host through Bluebrry, and up until Dec 11, things were working fine. I had created a legacy media server, input the entire url to our public directory, and then I would just input the file name in the individual media file. 

Since 12/11, it not just writes the file name to the xml. It still works just fine to play the files through a series/study view on the website (so the legacy server is working fine for that).

Created a public ticket on JBS forum: http://www.joomlabiblestudy.org/index.php?option=com_ats&view=Ticket&id=30&Itemid=519

you can view the xml file here: https://cbcneenah.org/sermons.xml

System info: php 5.6
JBS 9.0.8
Joomla 3.6.5

**Comment by bcordis** [comment]
Fixed in 9.0.10
