### ISSUE TITLE
Teacher list View Problems.

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Joomla-Bible-Study#725]
In my study list view, i show the thumbnail. In the admin template, i selected in display items list 1, teacher image in the span row, Rounded, Pull left. Nothing show. Same bug with teacher list view...

**Comment by tomfuller2** [comment]
I'm working on this. Can you give me ftp credentials to the new host? 
This starts in lib/listing.php on line 751 with a check of whether a rowspan item has been selected in the template. Need to check the variables on through that function.

**Comment by bcordis** [comment]
@tomfuller2 What is the status here?

**Comment by tomfuller2** [comment]
I think I fixed this. The $span variable was being reset so I added another layer of checks. 
https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/commit/f58629677b27dc3a341cd6dd5e4dc2c9ccf20f6e
