### ISSUE TITLE
Migration breaks with '0 Error decoding JSON data: Syntax error'; Database is destroyed

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#760]
I managed to workaround the installation bug and get an installation that seems to be ok. Afterwars I started the Migration. Migration of an jbs database 8.0.0 ends up in a JSON decoding error. Stack:

Call stack
--
# | Function | Location
1 | () | JROOT\libraries\vendor\joomla\registry\src\Format\Json.php:72
2 | Joomla\Registry\Format\Json->stringToObject() | JROOT\libraries\vendor\joomla\registry\src\Registry.php:366
3 | Joomla\Registry\Registry->loadString() | JROOT\administrator\components\com_biblestudy\helpers\params.php:68
4 | JBSMParams::getAdmin() | JROOT\administrator\components\com_biblestudy\helpers\biblestudyhelper.php:377
5 | JBSMBibleStudyHelper::debug() | JROOT\administrator\components\com_biblestudy\api.php:96
6 | require_once() | JROOT\administrator\components\com_biblestudy\biblestudy.php:24
7 | require_once() | JROOT\libraries\cms\component\helper.php:389
8 | JComponentHelper::executeComponent() | JROOT\libraries\cms\component\helper.php:364
9 | JComponentHelper::renderComponent() | JROOT\libraries\cms\application\administrator.php:98
10 | JApplicationAdministrator->dispatch() | JROOT\libraries\cms\application\administrator.php:156
11 | JApplicationAdministrator->doExecute() | JROOT\libraries\cms\application\cms.php:265
12 | JApplicationCms->execute() | JROOT\administrator\index.php:51

Afterwards the jbs database is destroyed, none of the pages can be displayed.

**Comment by bcordis** [comment]
@st-anton are you able to send me the DB before starting the migration so I can see where the error is occurring.

**Comment by st-anton** [comment]
I think, you want to test with my exported database of BS 8.0.0. I send by private email.

**Comment by bcordis** [comment]
Export of 8.0.0 db is corrupt and can’t be migrated without cleaning up the code. We have a error in the 8.x version of exporting the db.

Closing as this is a bug that we have fixed in others but will have to work with clients on case by case.
