### ISSUE TITLE
Frontend new Study: Table Sermon is not supported. File not found

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#763]
When klicking the 'new' button for a new study, there is a message JLIB_APPLICATION_ERROR_TABLE_NAME_NOT_SUPPORTED
![grafik](https://user-images.githubusercontent.com/2517417/32194261-2c625ed4-bdba-11e7-8d3a-f97af2fdab74.png)

**Comment by st-anton** [comment]
new study link:
[http://localhost/feg_j37/predigtarchiv/predigt-neu-oder-aendern/sermons?task=sermon.edit](http://localhost/feg_j37/predigtarchiv/predigt-neu-oder-aendern/sermons?task=sermon.edit)
new media link:
[http://www.muenchen-nord.feg.de/predigtarchiv/medien-neu-oder-aendern/mediafileform?task=mediafileform.edit](http://www.muenchen-nord.feg.de/predigtarchiv/medien-neu-oder-aendern/mediafileform?task=mediafileform.edit)

Shouldn't den new study link be message instead of sermon?

**Comment by bcordis** [comment]
@st-anton Looking into the problem now. This was working on many systems so I'll find the bug.

**Comment by st-anton** [comment]
Unfortunatelly still in 9.1.4 This forces me (admin) to release every sermon, as I do not want to allow our media recorder guys to enter the backend.
The 'new media' link is working, the 'new study' link is broken.

**Comment by bcordis** [comment]
@st-anton Looking into the problem now. We have verified that it is now working.

**Comment by bcordis** [comment]
@st-anton working with @tomfuller2 on whether the other files are needed. Not sure where this came from looking into it.

**Comment by tomfuller2** [comment]
I think Brent meant to say that it is NOT working.

**Comment by tomfuller2** [comment]
We've fixed this. Two links were wrong - they hadn't been updated. In the next release we'll fix it. 

If you want to fix it in the meantime I can give you the files or tell you where to change.

**Comment by st-anton** [comment]
Thanks a lot! I found your commit and confirm, that this fixes the bug.

**Comment by bcordis** [comment]
Closing issue.
