### ISSUE TITLE
Can not install 9.2.0 zip pkg

### ISSUE THREAD

**Issue by nixthing** [Joomla-Bible-Study/Joomla-Bible-Study#803]
When trying to install get, 404 Component not found, error.
After logging back in shows in Components but if I try to launch I get, 1146 Table 'db770782160.#__bsms_admin' doesn't exist, error. However examining the databases, db770782160 is indeed there. 
Using Joomla 3.9.10.

**Comment by tomfuller2** [comment]
Is this a fresh install? If so, I would recommend deleting the tables with _bsms and attempting the install again. The table names should be db770782160_bsms_... - the # should not be there. Let us know what happens and we'll go from there!

**Comment by nixthing** [comment]
Yes fresh install, now I have to try and get the site back up.I can't access the site at all, back end  or front end. Just get db access errors.Seems that the only option right now is to restore from s back up w/o JBS and try to install again.Thank you for your response will let you know how it goes once I can get site working again.On Aug 5, 2019 11:07 AM, Tom Fuller <notifications@github.com> wrote:Is this a fresh install? If so, I would recommend deleting the tables with bsms and attempting the install again. The table names should be db770782160_bsms... - the # should not be there. Let us know what happens and we'll go from there!

**Comment by bcordis** [comment]
@nixthing Can you update us on this? let us know if you were able to install again and see a fresh install work. thanks.

Leaving ticket open for 9 days and will close.

**Comment by nixthing** [comment]
I did a fresh I install replied with email I think it was around the 5th of August. To your question, yes a fresh install worked, but still had to recreate my site. Fortunately it was a test site.Thank you.On Sep 3, 2019 5:04 AM, Brent Cordis <notifications@github.com> wrote:@nixthing Can you update us on this? let us know if you were able to install again and see a fresh install work. thanks.
Leaving ticket open for 9 days and will close.
